---
title: "downstream_analysis_RV144"
author: "Adam Pelletier"
date: "7/28/2019"
output: html_document
---

```{r setup, message = FALSE, warning=FALSE}
suppressPackageStartupMessages(library(rstudioapi))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(pheatmap))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(biomaRt))
suppressPackageStartupMessages(library(GSEABase))
suppressPackageStartupMessages(library(fgsea))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(tibble))
suppressPackageStartupMessages(library(GSVA))
suppressPackageStartupMessages(library(cluster))
suppressPackageStartupMessages(library(apeglm))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(sva))
suppressPackageStartupMessages(library(affy))
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(GSVA))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(janitor))
suppressPackageStartupMessages(library(SuperExactTest))

library(survminer)
library(survival)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(getwd())
```

```{r }

setup_dir <- function(dir_string) { 
  ### Verifies creates a directory if it doesn't exist. Returns the dir_path
  if (dir.exists(dir_string)){
    dir_set <- dir_string
  } else {
    dir.create(dir_string) 
    dir_set <- dir_string
  }
  return(dir_set)
}


inputDir <- setup_dir("input")
outDir <- setup_dir("output")

genesetsDir <- setup_dir("../input/genesets")
figureDir <- setup_dir(file.path(outDir,"figures"))
dataOutDir <- setup_dir(file.path(outDir,"data"))


```

```{r fgsea_func}

fgsea_function_topT <- function(x,gmtfile, method = "logp", p_thr = 0.05, n.perm = 10000, maxSize = 500, minSize = 15) {
  ###function to do preranked geneset enrichment using fgsea using a given 1. topTable input and 2.gmt file path
  if(!method %in% c("logp", "T")){
    stop("Invalid method for fgsea_function. Options are 'logp' or 'T")
  }
  topTable_all <- x %>% as.data.frame(.) %>% 
            rownames_to_column("Illumina_ID") %>% 
            filter(!SYMBOL %in%  c("", "---")) %>%
            # group_by(SYMBOL) %>%
            # # summarise(mean_logFC = mean(logFC),
            # #           mean_t = mean(t),
            # #           mean_P.value = mean(P.Value)) %>%
            # #filter(!duplicated(BROAD.Gene.Symbol)) %>%
            # ungroup(.) %>%
            column_to_rownames("SYMBOL")
  if(method == "logp") {
      topTable_all$rank_metric <- sign(topTable_all$t) *   -log(shrunk_deseq_output$P.Value)
      topTable_all <- topTable_all[order(-topTable_all$rank_metric),] 
      ranks <- topTable_all
      ranks_set <- setNames(ranks$rank_metric, row.names(ranks))
  } else if(method == "T") {
    topTable_all$rank_metric <- topTable_all$t 
      topTable_all <- topTable_all[order(-topTable_all$rank_metric),] 
      ranks <- topTable_all
      ranks_set <- setNames(ranks$rank_metric, row.names(ranks))
  }
  pathways <- gmtPathways(gmtfile)
  fgseaRes<-fgsea(pathways,ranks_set,minSize=minSize,maxSize=maxSize,nperm=n.perm)
  fgseaRes<- fgseaRes[fgseaRes$pval <=p_thr,]
  fgseaRes<-fgseaRes[order(fgseaRes$padj),]
  fgseaRes<-fgseaRes[!is.na(fgseaRes$padj),]
  return(fgseaRes)
}

fgsea_output_topT <- function(fgsea_vector,
                         eset_contrast,
                         outcome,
                         geneset_list,
                         geneset,
                         fileDir,
                         method = "shLFC",
                         p_thr = 0.05, 
                         maxSize = 500) {
  if(length(fgsea_vector[[outcome]]) == 0) {
    fgsea_list <- list()
  } else {
    fgsea_list <- fgsea_vector[[outcome]]
  }
  fgsea_list[[geneset]]$geneset_file <- geneset_list[[geneset]]
  fgsea_list[[geneset]]$output <- fgsea_function_topT(eset_contrast, geneset_list[[geneset]], method = method,
                                                      p_thr = p_thr, maxSize = maxSize)
  write.csv(as.data.frame(fgsea_list[[geneset]]$output[,c(1:7)]), 
          file=file.path(fileDir,paste(outcome,geneset,method,"gsea.csv", sep="_")), 
          quote = FALSE)
  fgsea_vector[[outcome]] <- fgsea_list
  return(fgsea_vector)
}

```



```{r ORA_func}


hypergeom_ORA <- function(genelist, geneset_ids, N){
  intersect <- intersect(genelist, geneset_ids)
  m <- length(genelist)
  N <- N
  n <- N - m
  k <- length(geneset_ids)
  x <- length(intersect)

  
  if(x > 0 ){
    p.value <- phyper(q = x - 1 , m = m, n = n, k = k, lower.tail = F)
    out <- data.frame("p.value" = p.value, "leadingEdge" = paste(intersect, collapse = "; "),
                      "n_genes" = x)
  } else { 
    out <- data.frame("p.value" = 1, "leadingEdge" = "",
                      "n_genes" = "")
   
    }
  
  return(out)
}

ORA_test <- function(toptable, geneID_column = "SYMBOL",  pthr = 0.05, padj = 1, genesetColl,
                     directional = T){
  require(checkmate)
  coll = makeAssertCollection()
  assertDataFrame(toptable, null.ok = F, .var.name = "toptable",
              add = coll)
  if(!class(genesetColl) %in% c('GeneSetCollection', 'GeneSet')){
    coll$push("variable 'genesetColl' not of the GeneSetCollection or GeneSet class from GSEABase. Provide a valid object.")
   
  }

  assertCharacter(geneID_column, null.ok = F, max.len = 1, 
                  .var.name = "geneID_column", add = coll)
  assertNumeric(pthr, lower = 0, upper = 1, null.ok = F, .var.name = "pthr", max.len = 1,
              add = coll)
  assertNumeric(padj, lower = 0, upper = 1, null.ok = F, .var.name = "padj", max.len = 1,
              add = coll)
  assertLogical(directional, null.ok = F, .var.name = "directional", max.len = 1,
              add = coll)
  
  reportAssertions(coll)
  
  if(length(intersect(colnames(toptable), y = geneID_column)) == 0){
    coll$push(paste("Column ", geneID_column, 
                    " not found in toptable. Please provide valid column", sep = ""))
  }
  
  reportAssertions(coll)
  
  if(length(intersect(toptable[[geneID_column]], y = unique(unlist(geneIds(genesetColl), 
                                                                   use.names = F)))) == 0){
    coll$push('Gene Identifiers not found in Geneset Collection')
  }
  reportAssertions(coll)
  
  
  
  df <- toptable %>%
        as.data.frame(.) %>%
        dplyr::rename(geneid_coll = geneID_column) %>%
        filter(!geneid_coll %in%  c("", "---")) %>%
        filter(!is.na(geneid_coll)) %>%
        separate_rows(geneid_coll, sep = " /// ") %>%
        mutate(DIR = ifelse(sign(logFC) == 1, "UP", "DN"))
 
  filt <- df %>%
          filter(P.Value < pthr) %>%
          filter(adj.P.Val < padj) 
  
  idLS <- list()
  if(directional){
    idLS[["UP"]] <- unique(filt[filt$DIR == "UP",][["geneid_coll"]])
    idLS[["DN"]] <- unique(filt[filt$DIR == "DN",][["geneid_coll"]])
  } else {
    idLS[["ALL"]] <- unique(filt[["geneid_coll"]])
  }
          
  ORA_out <- do.call("rbind", lapply(names(idLS), function(x){
  #ORA_out <- sapply(names(idLS), simplify = F, USE.NAMES = T, function(x){
  #    out <- hypergeom_ORA(idLS[[x]], geneset_ids = geneIds(genesetColl)[[1]],
  #                   N = length(unique(df$geneid_coll)))
  #   
  # })
      if(class(genesetColl) == "GeneSetCollection"){
        #out <- sapply(names(genesetColl), simplify = F, USE.NAMES = T, function(y){
        out <- do.call("rbind", lapply(names(genesetColl), function(y){
          gs <- genesetColl[names(genesetColl) == y]
          ins <- hypergeom_ORA(idLS[[x]], geneset_ids = geneIds(gs)[[1]],
                       N = length(unique(df$geneid_coll))) %>%
                mutate(direction = x,
                       pathway = y) %>%
                        dplyr::select(pathway, direction, everything())
        #})
        #out <- do.call("rbind", lapply(names(genesetColl), function(y){
          
        }))
      } else {

        out <- hypergeom_ORA(idLS[[x]], geneset_ids = geneIds(genesetColl)[[1]],
                       N = length(unique(df$geneid_coll))) %>%
                mutate(direction = x,
                       pathway = names(genesetColl)[[1]]) %>%
                        dplyr::select(pathway, direction, everything())
    }
  }))
  #})  
  
  ORA_out <- ORA_out %>% 
              mutate(padj = p.adjust(p.value)) %>%
              arrange(p.value) %>%
              mutate(logp = ifelse(direction == "DN", log10(p.value),
                                   -log10(p.value))) %>%
              dplyr::select(pathway, direction, p.value, padj, logp, n_genes, leadingEdge )

  return(ORA_out)
}



```




```{r ORA_RV144_fits}


ORA_LS <- list("post-vaccination" =ORA_test(fits_rv144_prepost_vaxx$topTable, 
                                 genesetColl = CHEA_CREB, padj = 1),
     "HIV_acquisition" =  ORA_test(fits_rv144_hiv_pos$topTable, 
                                   genesetColl = CHEA_CREB, padj = 1),
     "wk26_V1V2_titers" = ORA_test(fits_rv144$topTable, genesetColl = CHEA_CREB, padj = 1))

CREB_ORA_df <- do.call("rbind", lapply(names(ORA_LS), function(x){
    out <- ORA_LS[[x]] %>%
             mutate(contrast = x) %>%
            filter(pathway == "CREB1") %>%
            dplyr::select(contrast, everything()) %>%
            dplyr::select(-leadingEdge, -n_genes ) 
        
}))

write_tsv(CREB_ORA_df,path = "output/data/ORA_RV144_CREB1_CHEA.txt" )



CREB_ORA_df2 <- CREB_ORA_df %>%
                  mutate(expected = ifelse(contrast == "HIV_acquisition", "DN", "UP")) #%>%
                  #filter(direction == expected) #%>%
    

CREB_ORA_barplot <- ggplot(CREB_ORA_df, aes(x = contrast, y = logp, fill = direction)) +
                  geom_bar(stat='identity', width=0.6, position = "stack") + 
                  theme_bw() +
                  xlab("Contrast") + 
                  ylab("CREB1 signed -log(p-value)") + 
                  theme(axis.title = element_text(family = "Times", face="bold", size=12)) +
                  theme(axis.text = element_text(family = "Times", face="bold", size=8)) +
                  geom_hline(yintercept=-log10(0.05), color = "gray", linetype = "dashed") +
                  geom_hline(yintercept=log10(0.05), color = "gray", linetype = "dashed") +
                  geom_hline(yintercept=0, color = "black", size=0.5) +
                  scale_fill_manual(values=c("blue", "red")) +
                  # scale_fill_gradientn(colours = colorRampPalette(colors = c("blue", "white",
                  #                                                            "red"))(500),
                  #                              limits = c(-max(abs(CREB_ORA_df$logp)), 
                  #                                         max(abs(CREB_ORA_df$logp)))) +
                          theme(text = element_text(size = 12),
                                axis.text = element_text(size = 12),
                                axis.title = element_text(size = 14, face = 'bold')) + 
                          #ggtitle("Immune related genesets vs HIV Acquisition")  + 
                          coord_flip() 

ggsave(CREB_ORA_barplot, filename = "output/figures/ORA_CREB1_barplot_stacked_RV144.pdf")



```


```{r CHEA_gsea_tables}

gsea_creb_LS <- list("postvaccination" = fgsea_analysis_prepost$post_VACCINE$CHEA$output,
     "HIV_acquisition" =  fgsea_analysis_hiv_pos$`HIV_Pos_VACCINE-HIV_Neg_VACCINE`$CHEA$output,
     "wk26_V1V2_titers" = fgsea_analysis_titers$wk26_V1V2$CHEA$output)

CREB_gsea_df_summ <- do.call("rbind", lapply(names(gsea_creb_LS), function(x){
    out <- gsea_creb_LS[[x]] %>%
             mutate(contrast = x) %>%
            filter(pathway == "CREB1") %>%
            dplyr::select(contrast, everything()) %>%
            dplyr::select(-leadingEdge, -size, -nMoreExtreme ) 
        
}))

write_tsv(CREB_gsea_df_summ,path = "output/data/GSEA_RV144_CREB1_CHEA_summary.txt" )





```

```{r gsea_hm}
gsea_hm <- function(fgsea_object,
                    contrasts,
                    geneset,
                    pval_thr,
                    filename, 
                    subset = c(),
                    max_gs = 10,
                    clusterRowsGap = FALSE){
  pathways <- list()
  df_list <- list()
  for(i in contrasts) {
    index <- which(contrasts == i)
    if(length(subset) == 0){
      df_temp <- fgsea_object[[i]][[geneset]][["output"]] %>%
      as.data.frame(.) %>%
      filter(padj <= pval_thr) %>%
      dplyr::select(pathway,NES) %>%
      dplyr::slice(.,1:max_gs) %>%
      .$pathway
    } else {
      df_temp <- fgsea_object[[i]][[geneset]][["output"]] %>%
      as.data.frame(.) %>%
      filter(padj <= pval_thr) %>%
      filter(grepl(paste(subset, collapse="|"), pathway)) %>%
      dplyr::select(pathway,NES) %>%
      dplyr::slice(.,1:max_gs) %>%
      .$pathway
    }
    
    pathways[[i]] <- df_temp
  }
  total_pathway <- unique(unlist(pathways))
  for(i in contrasts) {
    index <- which(contrasts == i)
    if(length(subset) == 0){
      df_temp <- fgsea_object[[i]][[geneset]][["output"]] %>%
      as.data.frame(.) %>%
      filter(pathway %in% total_pathway) %>%
      dplyr::select(pathway,NES) %>%
      #dplyr::slice(.,1:max_gs) %>%
      mutate(contrast = i)
    } else {
      df_temp <- fgsea_object[[i]][[geneset]][["output"]] %>%
      as.data.frame(.) %>%
      filter(pathway %in% total_pathway) %>%
      filter(grepl(paste(subset, collapse="|"), pathway)) %>%
      dplyr::select(pathway,NES) %>%
      mutate(contrast = i)
    }
    
    df_list[[i]] <- df_temp
  }
  merged_df <- do.call("rbind", df_list) %>% spread(contrast, NES)
  if(dim(merged_df)[1] > 0){
    df <- merged_df %>%
    gather(contrast,NES,-pathway) %>%
    mutate(NES = ifelse(is.na(NES), 0 , NES)) %>%
    mutate(NES = as.numeric(NES)) %>%
    spread(contrast,NES) %>%
    column_to_rownames("pathway") %>%
    as.matrix(.)
  
  
  
    paletteLength <- 500
    colorLS <- colorRampPalette(colors = c("blue", "cyan",
                                           "white",
                                          "yellow", "red"))(paletteLength)
  
    # myBreaks <- c(seq(min(df), 0, length.out=ceiling(paletteLength/2) + 1),
    #             seq(max(df)/paletteLength, max(df), length.out=floor(paletteLength/2)))
    
    if(dim(df)[1] > 1){
      clusterFlag <- TRUE
    } else {
      clusterFlag <- FALSE
    }
    
    
    topScale <- max(abs(min(df)),abs(max(df)))
    print(topScale)
    myBreaks <- seq(-topScale, topScale, length.out=paletteLength)
    hm_object <- list()
    if (clusterRowsGap == FALSE) {
      p <- pheatmap(df,
               main = paste("GSEA_",geneset, sep=""),
                    color = colorLS,
                    fontsize= 6,
                    cellheight = 6,
                    cellwidth = 6,
                    show_colnames = TRUE,
                    annotation_names_row = FALSE,
                    cluster_cols = FALSE,
                    cluster_rows = clusterFlag,
                    breaks = myBreaks,
                    treeheight_row = 2,
               filename = filename)
      hm_object$clusterRow <- "none"
    } else {
      p_temp <- pheatmap(df)
      cluster_annot <- heatmap_gap_clustering(p_temp, K.max = 15)
      dev.off()
      tiff(file = file.path(figureDir,paste(filename,".tiff", sep="")), family=journal_font)
      p <- pheatmap(df,
               main = paste("GSEA_",geneset, sep=""),
                    color = colorLS,
                    fontsize= 6,
                    cellheight = 6,
                    cellwidth = 6,
                    show_colnames = TRUE,
                    annotation_names_row = FALSE,
                    cluster_cols = FALSE,
                    breaks = myBreaks,
                    annotation_row = cluster_annot$df["clusterID"])
      dev.off()
  
  
      hm_object$clusterRow <- cluster_annot
    }
    hm_object$plot <- p
    return(hm_object)
  }
}

```

```{r gsea_titers, echo=FALSE}
# geneset_list <- list(c2 = file.path(genesetsDir,
#                                         "c2.all.v6.1.symbols.gmt.txt"),
#                      c3 = file.path(genesetsDir,
#                                         "c3.all.v6.1.symbols.gmt.txt"),
#                      CHEA = file.path(genesetsDir,
#                                         "CHEA-tf.gmt"),
#                      interferome = file.path(genesetsDir,
#                                         "interferome.isg.gmt"))


GSEA_dir <- setup_dir(file.path(dataOutDir, "GSEA"))
fgsea_analysis_titers <- list()


for(j in names(geneset_list)) {
  if(j == "CHEA"){
    size <- 5000
  } else {
    size <- 500
  }
  fgsea_analysis_titers  <- fgsea_output_topT(fgsea_analysis_titers ,
                             eset_contrast = fits_rv144$topTable,
                             outcome = "wk26_V1V2",
                             geneset_list = geneset_list,
                             geneset = j,
                             fileDir = GSEA_dir,
                             p_thr = 0.99,
                             method = "T", 
                             maxSize = size)
  if(dim(fgsea_analysis_titers[["wk26_V1V2"]][[j]]$output)[1] >0){
    print(c("wk26_V1V2",j,dim(fgsea_analysis_titers[["wk26_V1V2"]][[j]]$output)[1]))
  }
}

for(j in names(geneset_plus)) {
  if(j == "CHEA"){
    size <- 5000
  } else {
    size <- 500
  }
  fgsea_analysis_titers  <- fgsea_output_topT(fgsea_analysis_titers ,
                             eset_contrast = fits_rv144$topTable,
                             outcome = "wk26_V1V2",
                             geneset_list = geneset_plus,
                             geneset = j,
                             fileDir = GSEA_dir,
                             p_thr = 0.99,
                             method = "T", 
                             maxSize = size)
  if(dim(fgsea_analysis_titers[["wk26_V1V2"]][[j]]$output)[1] >0){
    print(c("wk26_V1V2",j,dim(fgsea_analysis_titers[["wk26_V1V2"]][[j]]$output)[1]))
  }
}



save(fgsea_analysis_titers,file = "gsea_analysis_titers_RV144.RData" )


```



```{r titer_corr_figures}



CREB_subset <- c("CREB", "GPCR", "DARPP", "PKA", "CHEMOKINE", "CXCR[0-9]+", "CCR[0-9]+", "ATF1", "EPAC")
genesets_figs <- c("c2", "c3", "CHEA")




  for(j in genesets_figs){
    gsea_hm(fgsea_analysis_titers, 
        contrasts = names(fgsea_analysis_titers ),
        geneset = j,
                    pval_thr = 0.05,
                    filename  = paste("output/figures/titers/",j,"_gsea_titers_RV144","_CREB.pdf", sep = ""), 
                    clusterRowsGap = FALSE,
                    max_gs = 15,
                    subset = CREB_subset
                    )
    
    gsea_hm(fgsea_analysis_titers , 
        contrasts = names(fgsea_analysis_titers ),
        geneset = j,
                    pval_thr = 0.05,
                    filename  = paste("output/figures/titers/",j,"_gsea_titers_RV144",".pdf", sep = ""), 
                    clusterRowsGap = FALSE,
                    max_gs = 15
                    )

}



study36_CHEA <- readLines("../output/data/titers_postvaxx_study36_intersect_CHEA.txt")

gsea_titers_chea_barplot <- fgsea_analysis_titers$wk26_V1V2$CHEA$output %>%
                            as.data.frame() %>%
                            #filter(pathway %in% study36_CHEA) %>%
                            arrange(desc(NES)) %>%
                            filter(padj < 0.05) %>%
                           # mutate(rank = rank(desc(abs(NES)))) %>%
                            dplyr::select(-leadingEdge)


gsea_prepost_chea_barplot <- fgsea_analysis_prepost$`post_VACCINE-pre_VACCINE`$CHEA$output %>%
                            as.data.frame() %>%
                            #filter(pathway %in% study36_CHEA) %>%
                            arrange(desc(NES)) %>%
                            filter(padj < 0.05) %>%
                            filter(NES > 0 ) %>%
                           # mutate(rank = rank(desc(abs(NES)))) %>%
                            dplyr::select(-leadingEdge)


gsea_prepost_GPCR_chemok_barplot <- fgsea_analysis_prepost$post_VACCINE$c2$output %>%
                            bind_rows(fgsea_analysis_prepost$post_VACCINE$c5$output) %>%
                            as.data.frame() %>%
                          #filter(grepl("GPCR|MIGRATION|CHEMOTAXIS|CHEMOKINE|CCR|CXCR|CX3CR", pathway)) %>%
                          filter(grepl("CYTOKINE|IL-[0-9]+|IFN|INTERFERON|IL[0-9]+", pathway)) %>%
                            arrange(desc(NES)) %>%
                            filter(pval < 0.05) %>%
                            filter(NES > 0 ) #%>%
                           # mutate(rank = rank(desc(abs(NES)))) %>%
                            #dplyr::select(-leadingEdge)
gsea_prepost_GPCR_chemok_barplot_env <- fgsea_analysis_prepost_env$post_VACCINE$c2$output %>%
                            bind_rows(fgsea_analysis_prepost_env$post_VACCINE$c5$output) %>%
                            as.data.frame() %>%
                          filter(grepl("GPCR|MIGRATION|CHEMOTAXIS|CHEMOKINE|CCR|CXCR|CX3CR", pathway)) %>%
                          #filter(grepl("CYTOKINE|IL-[0-9]+|IFN|INTERFERON|IL[0-9]+", pathway)) %>%
                            arrange(desc(NES)) %>%
                            filter(pval < 0.05) %>%
                            filter(NES > 0 ) 

CREB_post_ledge <- fgsea_analysis_prepost$`post_VACCINE-pre_VACCINE`$CHEA$output %>%
                            as.data.frame() %>%
                            filter(pathway == "CREB1") %>%
                            unnest(cols = "leadingEdge") %>%
                            .$leadingEdge

writeLines(CREB_post_ledge, con = "output/data/CREB1_psotvaxx_ledge.txt", sep = "\n")

gsea_barplot_func <- function(gsea_df, title = NULL){
  df <- gsea_df 
  topScale <- max(abs(df$NES))
  colorLS <- colorRampPalette(colors = c("blue", "white", "red"))(500)
  p <- ggplot(df, aes(x = reorder(pathway,NES), y = NES, fill = NES)) + 
        geom_bar(stat='identity', width=0.8, position = "identity") +
        theme_bw() + 
        xlab("Pathway") + 
        ylab("NES (Normalized Enrichment Score)") + 
        ggtitle(title) + 
        theme(axis.title = element_text(family = "Times", face="bold", size=12)) +
           theme(axis.text = element_text(family = "Times", face="bold", size=8)) +
        geom_hline(yintercept=0, color = "gray", size=0.5) +
        scale_fill_gradientn(colours = colorLS, limits = c(-topScale, topScale)) +
        coord_flip() 
  return(p)
}
gsea_titers_chea_barplot_intersect_p <- gsea_barplot_func(gsea_titers_chea_barplot[gsea_titers_chea_barplot$pathway %in%
                                                                                     study36_CHEA,])

pdf("output/figures/CHEA_gsea_titers_RV144_barplot_intersect.pdf", height = 5, width = 4)
gsea_titers_chea_barplot_intersect_p
dev.off()


gsea_prepost_chea_barplot_intersect_p <- gsea_barplot_func(gsea_prepost_chea_barplot[gsea_prepost_chea_barplot$pathway %in%
                                                                                     study36_CHEA,])

pdf("output/figures/CHEA_gsea_prepost_RV144_barplot_intersect.pdf", height = 5, width = 4)
gsea_prepost_chea_barplot_intersect_p 
dev.off()


gsea_titers_chea_barplot_p <- gsea_barplot_func(gsea_titers_chea_barplot)

pdf("output/figures/CHEA_gsea_titers_RV144_barplot_all.pdf", height = 8, width = 4)
gsea_titers_chea_barplot_p
dev.off()


gsea_prepost_chea_barplot_p <- gsea_barplot_func(gsea_prepost_chea_barplot)

pdf("output/figures/CHEA_gsea_prepost_RV144_barplot_all.pdf", height = 8, width = 4)
gsea_prepost_chea_barplot_p 
dev.off()



```

```{r gsea_titers, echo=FALSE}
geneset_list <- list(c2 = file.path(genesetsDir,
                                        "c2.all.v6.1.symbols.gmt.txt"),
                     c3 = file.path(genesetsDir,
                                        "c3.all.v6.1.symbols.gmt.txt"),
                     CHEA = file.path(genesetsDir,
                                        "CHEA-tf.gmt"),
                     interferome = file.path(genesetsDir,
                                        "interferome.isg.gmt"),
                     c5 = file.path(genesetsDir,
                                        "c5.all.v6.1.symbols.gmt.txt"),
                     c7 = file.path(genesetsDir, "c7.all.v6.1.symbols.gmt.txt"),
                     chipseq_overlap = "../../chip_seq/output/CHIP_transc_overlap.gmt")




GSEA_dir <- setup_dir(file.path(dataOutDir, "GSEA"))
fgsea_analysis_hiv_pos <- list()


for(j in names(geneset_list)) {
  if(j == "CHEA"){
    size <- 5000
  } else {
    size <- 500
  }
  fgsea_analysis_hiv_pos  <- fgsea_output_topT(fgsea_analysis_hiv_pos ,
                             eset_contrast = fits_rv144_hiv_pos$topTable,
                             outcome = "HIV_Pos_VACCINE-HIV_Neg_VACCINE",
                             geneset_list = geneset_list,
                             geneset = j,
                             fileDir = GSEA_dir,
                             p_thr = 0.99,
                             method = "T", 
                             maxSize = size)
  if(dim(fgsea_analysis_hiv_pos[["HIV_Pos_VACCINE-HIV_Neg_VACCINE"]][[j]]$output)[1] >0){
      print(c("HIV_Pos_VACCINE-HIV_Neg_VACCINE",j,
              dim(fgsea_analysis_hiv_pos[["HIV_Pos_VACCINE-HIV_Neg_VACCINE"]][[j]]$output)[1]))
  }
}



for(j in names(geneset_list)) {
  if(j == "CHEA"){
    size <- 5000
    out <- plotEnrichment()
  } 
  fgsea_analysis_hiv_pos  <- fgsea_output_topT(fgsea_analysis_hiv_pos ,
                             eset_contrast = fits_rv144_hiv_pos$topTable,
                             outcome = "HIV_Pos_VACCINE-HIV_Neg_VACCINE",
                             geneset_list = geneset_list,
                             geneset = j,
                             fileDir = GSEA_dir,
                             p_thr = 0.99,
                             method = "T", 
                             maxSize = size)
  if(dim(fgsea_analysis_hiv_pos[["HIV_Pos_VACCINE-HIV_Neg_VACCINE"]][[j]]$output)[1] >0){
      print(c("HIV_Pos_VACCINE-HIV_Neg_VACCINE",j,
              dim(fgsea_analysis_hiv_pos[["HIV_Pos_VACCINE-HIV_Neg_VACCINE"]][[j]]$output)[1]))
  }
}


# GSEA_dir <- setup_dir(file.path(dataOutDir, "GSEA"))
# fgsea_analysis_hiv_pos_env <- list()
# 
# 
# for(j in names(geneset_list)) {
#   if(j == "CHEA"){
#     size <- 5000
#   } else {
#     size <- 500
#   }
#   fgsea_analysis_hiv_pos_env  <- fgsea_output_topT(fgsea_analysis_hiv_pos_env ,
#                              eset_contrast = degs,
#                              outcome = "HIV_Pos_VACCINE-HIV_Neg_VACCINE_ENV",
#                              geneset_list = geneset_list,
#                              geneset = j,
#                              fileDir = GSEA_dir,
#                              p_thr = 0.99,
#                              method = "T", 
#                              maxSize = size)
#   if(dim(fgsea_analysis_hiv_pos_env[["HIV_Pos_VACCINE-HIV_Neg_VACCINE_ENV"]][[j]]$output)[1] >0){
#       print(c("HIV_Pos_VACCINE-HIV_Neg_VACCINE_ENV",j,
#               dim(fgsea_analysis_hiv_pos_env[["HIV_Pos_VACCINE-HIV_Neg_VACCINE_ENV"]][[j]]$output)[1]))
#   }
# }



save(fgsea_analysis_hiv_pos,file = "gsea_analysis_hiv_pos_RV144.RData" )


```

```{r titer_TF_overlap_immune}

c5_gmt <- getGmt(geneset_list$c5)
immune_filter_c5 <- c("IMMUNE","B_CELL","T_CELL", "DENDRITIC" ,"MONOCYTE" ,"CHEMOTAXIS","INTERLEUKIN","INTERFERON","INFLAMMATION", "MACROPHAGE", 
                      "ANTIGEN","LYMPHOCYTE","LEUKOCYTE","NF_KAPPAB","LYMPHOID","MYELOID", "INFLAMMASOME", "CYTOKINE", "CHEMOKINE", "TUMOR_NECROSIS_FACTOR", "HUMORAL")

immune_c5 <- c5_gmt[grepl(paste(immune_filter, collapse = "|"), names(c5_gmt))]

titer_tf <- fgsea_analysis_titers$wk26_V1V2$CHEA$output %>%
            filter(pathway %in% c("CREB1", "THAP11", "TBX5", "PDX1", "CCND1")) %>%
            unnest(cols = "leadingEdge") %>%
            mutate(immune_check = ifelse(leadingEdge %in% unique(unlist(geneIds(immune_c5), use.names = F)),1, 0)) %>%
            group_by(pathway) %>%
            #mutate(n = n()) %>%
            summarise(sum_immune = sum(immune_check),
                      n = n()) %>%
            mutate(relFreq = sum_immune/n) %>%
            ungroup()
write_tsv(titer_tf, path = "output/data/RV144_TF_titers_comparison_immune.txt")

```


```{r CHIP_Seq_overlap_gsea}
contrasts_concat <- list("wk26_V1V2" = fgsea_analysis_titers$wk26_V1V2, 
             "HIV_acquisition" = fgsea_analysis_hiv_pos$`HIV_Pos_VACCINE-HIV_Neg_VACCINE`,
             "postvaxx" = fgsea_analysis_prepost$post_VACCINE)

fgsea_creb_chip <- do.call("rbind", lapply(names(contrasts_concat), function(x){
  full_creb <- contrasts_concat[[x]]$CHEA$output %>%
                dplyr::select(-leadingEdge) %>%
                filter(pathway == "CREB1") %>%
                mutate(pathway = paste("FULL_CHEA", pathway, sep = "_"))
      
  out <- contrasts_concat[[x]]$chipseq_overlap$output %>%
          dplyr::select(-leadingEdge) %>%
          bind_rows(full_creb) %>%
          mutate(contrast = x) %>%
          mutate(logp = sign(NES) * -log10(pval))
    
}))


RV144_overlap_barplot <- ggplot(fgsea_creb_chip, aes(x = pathway, 
                                                           y = logp, fill = logp)) + 
                          geom_bar(stat='identity', width=0.6, position = "identity") + 
                          theme_bw() +
                           xlab("Pathway") + 
                          ylab("signed -log10(p.value)") + 
                          theme(axis.title = element_text(family = "Times", face="bold", size=12)) +
                           theme(axis.text = element_text(family = "Times", face="bold", size=8)) +
                          geom_hline(yintercept=0, color = "gray", size=0.5) +
                          scale_fill_gradientn(colours = colorRampPalette(colors = c("blue", "white", "red"))(500),
                                               limits = c(-max(abs(fgsea_creb_chip$logp)), 
                                                          max(abs(fgsea_creb_chip$logp)))) +
                          theme(text = element_text(size = 12),
                                axis.text = element_text(size = 12),
                                axis.title = element_text(size = 14, face = 'bold')) + 
                          #ggtitle("Immune related genesets vs HIV Acquisition")  + 
                          coord_flip() +
                          facet_wrap(~contrast, ncol = 1)


ggsave(RV144_overlap_barplot, filename = "output/figures/rv1144_chip-seq_overlap_barplot.pdf")
write_tsv(fgsea_creb_chip, path = "output/data/gsea_creb1_chip_overlap.tsv")




overlap_ledge_matr <- exprs(eset_BL_ave) %>%
                      as.data.frame() %>%
                      rownames_to_column("IlmnID") %>%
                      inner_join(.,fData(eset_BL_ave) %>% dplyr::select(IlmnID, SYMBOL), 
                                 by = "IlmnID" ) %>%
                      filter(SYMBOL %in% test2) %>%
                      dplyr::select(-IlmnID) %>%
                      column_to_rownames("SYMBOL") %>%
                      as.matrix()
titer_annot <- as.data.frame(pData(eset_BL_ave)) %>%
              




```

```{r hiv_pos_figures}



CREB_subset <- c("CREB", "GPCR", "DARPP", "PKA", "CHEMOKINE", "CXCR[0-9]+", "CCR[0-9]+", "ATF1", "EPAC")
genesets_figs <- c("c2", "c3", "CHEA")




  for(j in genesets_figs){
      gsea_hm(fgsea_analysis_hiv_pos, 
        contrasts = names(fgsea_analysis_hiv_pos ),
        geneset = j,
                    pval_thr = 0.05,
                    filename  = paste("output/figures/hiv_pos/",j,"_gsea_HIV_pos_RV144","_CREB.pdf", sep = ""), 
                    clusterRowsGap = FALSE,
                    max_gs = 15,
                    subset = CREB_subset
                    )
    
    gsea_hm(fgsea_analysis_hiv_pos , 
        contrasts = names(fgsea_analysis_hiv_pos ),
        geneset = j,
                    pval_thr = 0.05,
                    filename  = paste("output/figures/hiv_pos/",j,"_gsea_HIV_pos_RV144",".pdf", sep = ""), 
                    clusterRowsGap = FALSE,
                    max_gs = 15
                    )

}


HIV_pos_CHEA_CREB_LE <-  fgsea_analysis_hiv_pos$`HIV_Pos_VACCINE-HIV_Neg_VACCINE`$CHEA$output %>%
                          filter(pathway == "CREB1") %>%
                          unnest(.) %>%
                          .$leadingEdge

writeLines(HIV_pos_CHEA_CREB_LE,"output/data/CREB_hiv_acquisition_LE.txt")

CREB_titers_LE <- as.data.frame(fgsea_analysis_titers$wk26_V1V2$CHEA$output) %>% 
                  filter(pathway == "CREB1") %>%
                  unnest(cols = "leadingEdge") %>%
                  .$leadingEdge

writeLines(CREB_titers_LE, "output/data/CREB_rv144_titers_LE.txt")

CREB_filt_HIV_pos_df <- exprs(eset_ave) %>%
                        as.data.frame(.) %>%
                        rownames_to_column("IlmnID") %>%
                        gather(sample, value, -IlmnID) %>%
                        inner_join(., pData(eset_ave), by = c("sample" = "Sample name")) %>%
                        filter(stimulation == "DMSO" & treatment == "VACCINE") %>%
                        inner_join(., fData(eset_ave), by = "IlmnID") %>%
                        filter(SYMBOL %in% HIV_pos_CHEA_CREB_LE)

expr_mat_gsva_HIV_pos <- CREB_filt_HIV_pos_df %>%
                        dplyr::select(sample, SYMBOL, value) %>%
                        spread(sample, value) %>%
                        column_to_rownames("SYMBOL") %>%
                        as.matrix(.)

annot_gsva_HIV_pos <- CREB_filt_HIV_pos_df %>%
                        dplyr::select(sample, `HIV infection` ) %>%
                        unique(.) %>%
                        rowid_to_column("rowid") %>%
                        dplyr::select(-rowid) %>%
                        #unique(.) %>%
                        column_to_rownames("sample")

CHEA <- getGmt("../input/genesets/CHEA-tf.gmt")
CHEA_CREB <- CHEA[names(CHEA) == "CREB1"]

gsva_HIV_pos_CREB <- as.data.frame(gsva(expr_mat_gsva_HIV_pos, CHEA_CREB, method = "zscore"))
gsva_HIV_pos_CREB <- gsva_HIV_pos_CREB[,order(gsva_HIV_pos_CREB)] %>% as.matrix(.)
               
gsva_HIV_pos_gene_corr <-  exprs(eset_ave) %>%
                        as.data.frame(.) %>%
                        rownames_to_column("IlmnID") %>%
                        gather(sample, value, -IlmnID) %>%
                        inner_join(., pData(eset_ave), by = c("sample" = "Sample name")) %>%
                        filter(stimulation == "DMSO" & treatment == "VACCINE") %>%
                        inner_join(., fData(eset_ave), by = "IlmnID") %>%
                        dplyr::select(sample, SYMBOL, value) %>%
                        unique() %>%
                        filter(SYMBOL %in% geneIds(CHEA_CREB)$CREB1) %>%
                        group_by(SYMBOL) %>%
                        mutate(scaled = scale(value)) %>%
                        ungroup() %>%
                        dplyr::select(sample, scaled, SYMBOL) %>%
                        spread(sample, scaled) %>%
                        column_to_rownames("SYMBOL") %>%
                        as.matrix()


colorAssign <- function(valueVector, scale_limits = NULL, colors = c("blue", "white", "red"), length.vector = 500){
  colorLS <- colorRampPalette(colors = colors)(length.vector)  
  if(is.null(scale_limits)){
    breaks <- seq(-max(abs(valueVector)), max(abs(valueVector)), length.out = length.vector)
  } else {
    breaks <- seq(scale_limits[1], scale_limits[2], length.out = length.vector)
  }
  
  
  minBreak <- which(abs(breaks - min(valueVector)) == min(abs(breaks - min(valueVector))))
  maxBreak <- which(abs(breaks - max(valueVector)) == min(abs(breaks - max(valueVector))))
  return(colorLS[minBreak:maxBreak])
}



gsva_HIV_pos_gene_corr_stats <- as.data.frame(gsva_HIV_pos_gene_corr) %>%
                          rownames_to_column("SYMBOL") %>%
                          gather(sample, scaled, -SYMBOL) %>%
                          inner_join(., (as.data.frame(gsva_HIV_pos_CREB) %>%
                                      rownames_to_column("pathway") %>%
                                      gather(sample, zscore, -pathway)), 
                                   by = "sample" ) %>%
                        filter(SYMBOL %in% HIV_pos_CHEA_CREB_LE) %>%
                          group_by(SYMBOL) %>%
                        do(model = cor.test(.$scaled , .$zscore, method = "spearman")) %>%
                        tidy(., model) %>%
                        ungroup() %>%
                        dplyr::rename(rho = "estimate") %>%
                        arrange(desc(rho)) %>%
                        mutate(ledge = ifelse(SYMBOL %in% HIV_pos_CHEA_CREB_LE, 
                                              "leading edge gene", NA)) %>%
                        mutate(row = SYMBOL) %>%
                         column_to_rownames("row") 


gsva_HIV_pos_gene_corr_stats_top <- gsva_HIV_pos_gene_corr_stats %>%
                        mutate(rank = rank(desc(rho))) %>%
                        filter(rank <= 200) 


# gsva_HIV_pos_gene_corr <- gsva_HIV_pos_gene_corr[gsva_HIV_pos_gene_corr_stats$SYMBOL,
#                                                  colnames(gsva_HIV_pos_CREB)]
gsva_HIV_pos_gene_corr <- gsva_HIV_pos_gene_corr[gsva_HIV_pos_gene_corr_stats_top$SYMBOL,
                                                 colnames(gsva_HIV_pos_CREB)]


hiv_infection_colors <- c("No" =  "#104E8B", "Yes" = "#8B0000")

gene_corr_hm_annot <- list("rho" = colorAssign(gsva_HIV_pos_gene_corr_stats_top$rho, 
                         scale_limits = c(-max(abs(gsva_HIV_pos_gene_corr_stats_top$rho)),
                                          max(abs(gsva_HIV_pos_gene_corr_stats_top$rho)))),
                         "CREB1 z-score" = colorAssign(gsva_HIV_pos_CREB, 
                         scale_limits = c(-max(abs(gsva_HIV_pos_CREB)),
                                          max(abs(gsva_HIV_pos_CREB)))),
                         "HIV infection" = c("No" =  "#104E8B", "Yes" = "#8B0000"))

gene_corr_hiv_pos_col_annot <- as.data.frame(t(gsva_HIV_pos_CREB)) %>%
                                rownames_to_column("sample") %>%
                                dplyr::rename(`CREB1 z-score` = "CREB1") %>%
                                inner_join(., pData(eset_ave) %>%
                                             rownames_to_column("sample"), by = "sample") %>%
                                column_to_rownames("sample")

hiv_pos_gene_corr_CREB_hm <- pheatmap(gsva_HIV_pos_gene_corr,
                              scale = "none",
                              cluster_rows = F,
                              cluster_cols = F,
                              color = colorAssign(gsva_HIV_pos_gene_corr),
                              annotation_col = gene_corr_hiv_pos_col_annot[c("CREB1 z-score",
                                                                             "HIV infection")],
                              annotation_row = gsva_HIV_pos_gene_corr_stats["rho"],
                              annotation_colors = gene_corr_hm_annot,
                              cellwidth = 1,
                              cellheight = 1, 
                              show_rownames = F, 
                              show_colnames = F,
                              filename = "output/figures/RV144_gene_corr_vs CREB1.pdf"
                              )




gsva_prepost_gene_corr <-  exprs(eset_ave_pilot) %>%
                        as.data.frame(.) %>%
                        rownames_to_column("IlmnID") %>%
                        gather(sample, value, -IlmnID) %>%
                        inner_join(., pData(eset_ave_pilot), by = c("sample" = "Sample name")) %>%
                        filter(grepl("DMSO_3h", sample)) %>%
                        inner_join(., fData(eset_ave_pilot), by = "IlmnID") %>%
                        filter(SYMBOL %in% prepost_CHEA_CREB_LE) %>%
                        filter(treatment == "VACCINE") %>%
                        filter(SYMBOL %in% geneIds(CHEA_CREB)$CREB1) %>%
                        group_by(SYMBOL) %>% 
                        mutate(scaled = scale(value)) %>%
                        ungroup() %>%
                        dplyr::select(sample, scaled, SYMBOL) %>%
                        spread(sample, scaled) %>%
                        column_to_rownames("SYMBOL") %>%
                        as.matrix()


gsva_prepost_gene_corr_stats <- as.data.frame(gsva_prepost_gene_corr) %>%
                          rownames_to_column("SYMBOL") %>%
                          gather(sample, scaled, -SYMBOL) %>%
                          inner_join(., (as.data.frame(gsva_prepost_CREB) %>%
                                      rownames_to_column("pathway") %>%
                                      gather(sample, zscore, -pathway)), 
                                   by = "sample" ) %>%
                        filter(SYMBOL %in% CREB_post_ledge) %>%
                          group_by(SYMBOL) %>%
                        do(model = cor.test(.$scaled , .$zscore, method = "spearman")) %>%
                        tidy(., model) %>%
                        ungroup() %>%
                        dplyr::rename(rho = "estimate") %>%
                        arrange(desc(rho)) %>%
                        mutate(ledge = ifelse(SYMBOL %in%  gsva_prepost_CREB, 
                                              "leading edge gene", NA)) %>%
                        mutate(row = SYMBOL) %>%
                         column_to_rownames("row") 

gsva_prepost_gene_corr <- gsva_prepost_gene_corr[gsva_prepost_gene_corr_stats$SYMBOL,
                                                 colnames(gsva_prepost_CREB)]


gene_corr_hm_annot <- list("rho" = colorAssign(gsva_prepost_gene_corr_stats$rho, 
                         scale_limits = c(-max(abs(gsva_prepost_gene_corr_stats$rho)),
                                          max(abs(gsva_prepost_gene_corr_stats$rho)))),
                         "CREB1" = colorAssign(gsva_prepost_CREB, 
                         scale_limits = c(-max(abs(gsva_prepost_CREB)),
                                          max(abs(gsva_prepost_CREB)))))

hiv_pos_gene_corr_CREB_hm <- pheatmap(gsva_HIV_pos_gene_corr,
                              scale = "none",
                              cluster_rows = F,
                              cluster_cols = F,
                              color = colorAssign(gsva_HIV_pos_gene_corr),
                              annotation_col = as.data.frame(t(gsva_HIV_pos_CREB))["CREB1"],
                              annotation_row = gsva_HIV_pos_gene_corr_stats[c("rho")],
                              annotation_colors = gene_corr_hm_annot,
                              cellwidth = 1,
                              cellheight = 0.5, 
                              show_rownames = F, 
                              show_colnames = F,
                              filename = "output/figures/RV144_gene_corr_vs CREB1.pdf"
                              )




HIV_pos_hm_CREB <- pheatmap(gsva_HIV_pos_CREB, 
                            annotation_col = annot_gsva_HIV_pos["HIV infection"],
                            cluster_rows = FALSE,
                            show_colnames = FALSE,
                            scale = "row",
                            cellheight = 20,
                            cellwidth = 3, 
                            color =  colorRampPalette(colors = c("blue","white","red"))(500),
                            cluster_cols = FALSE,
                            filename = file.path(figureDir,"hiv_pos/SLE_CREB_CHEA_HIV_pos.pdf"),
                            height = 6,
                            width = 16,
                            fontsize = 6)


write.csv(fgsea_analysis_hiv_pos$`HIV_Pos_VACCINE-HIV_Neg_VACCINE`$CHEA$output %>% 
            filter(pathway == "CREB1") %>% 
            dplyr::select(-leadingEdge),
          file = file.path(dataOutDir,"HIV_pos_GSEA_table.csv"))


gsva_HIV_pos_CREB_boxplot <- t(gsva_HIV_pos_CREB) %>%
                              as.data.frame(.) %>%
                              rownames_to_column("SampleID") %>%
                              filter(SampleID %in% logit_downsampling_id$SampleID) %>%
                              inner_join(., pData(eset_ave) %>% rownames_to_column("SampleID"), by = "SampleID" ) %>%
                              mutate(`HIV infection` = ifelse(`HIV infection` == "Yes", "HIV pos", "HIV neg" )) %>%
                              dplyr::rename(HIV_infection  = `HIV infection`) %>%
                              ggboxplot(., x = "HIV_infection", y = "CREB1", color = "HIV_infection", 
                                        palette = c("dodgerblue4","darkred"),
                              add = "jitter", outlier.shape = NA) +
                              #stat_compare_means(label = "p.signif", label.x = 1.5, method = "wilcox.test") +
                              xlab("HIV infection") +
                              ylab("CREB1 Z-score")

pdf(file.path(figureDir,"hiv_pos/SLE_CREB_CHEA_HIV_pos_boxplot.pdf"), height = 4, width = 4)
gsva_HIV_pos_CREB_boxplot
dev.off()

gsva_HIV_pos_titers

HIV_pos_titers <- t(gsva_HIV_pos_CREB) %>%
                              as.data.frame(.) %>%
                              rownames_to_column("SampleID") %>%
                              inner_join(., pData(eset_ave) %>% rownames_to_column("SampleID"), by = "SampleID" ) %>%
                              mutate(`HIV infection` = ifelse(`HIV infection` == "Yes", "HIV pos", "HIV neg" )) %>%
                              dplyr::rename(HIV_infection  = `HIV infection`) %>%
                              left_join(., titers, by = c("donor" = "pin")) %>%
                              rename(V1V2 = "primary_v2_gp70_v1v2_wk26") %>%
                              ggboxplot(., x = "HIV_infection", y = "V1V2", color = "HIV_infection", 
                                        palette = c("dodgerblue4","darkred"),
                              add = "jitter", outlier.shape = NA) +
                              stat_compare_means(label = "p.signif", label.x = 1.5, method = "wilcox.test") +
                              xlab("HIV infection") +
                              ylab("Week 26 V1V2 IgG titer")                              
  

pdf(file.path(figureDir,"hiv_pos/HIV_pos__V1V2_boxplot.pdf"), height = 4, width = 4)
HIV_pos_titers
dev.off()

```


```{r gsea_prepost, echo=FALSE}
geneset_list <- list(c2 = file.path(genesetsDir,
                                        "c2.all.v6.1.symbols.gmt.txt"),
                     c3 = file.path(genesetsDir,
                                        "c3.all.v6.1.symbols.gmt.txt"),
                     CHEA = file.path(genesetsDir,
                                        "CHEA-tf.gmt"),
                     interferome = file.path(genesetsDir,
                                        "interferome.isg.gmt"),
                     c5 = file.path(genesetsDir,
                                        "c5.all.v6.1.symbols.gmt.txt"))


GSEA_dir <- setup_dir(file.path(dataOutDir, "GSEA"))
fgsea_analysis_prepost <- list()


for(j in names(geneset_list)) {
  if(j == "CHEA"){
    size <- 5000
  } else {
    size <- 500
  }
  fgsea_analysis_prepost  <- fgsea_output_topT(fgsea_analysis_prepost ,
                             eset_contrast = fits_rv144_prepost_vaxx$topTable,
                             outcome = "post_VACCINE",
                             geneset_list = geneset_list,
                             geneset = j,
                             fileDir = GSEA_dir,
                             p_thr = 0.99,
                             method = "T", 
                             maxSize = size)
  if(dim(fgsea_analysis_prepost[["post_VACCINE"]][[j]]$output)[1] >0){
      print(c("post_VACCINE",j,
              dim(fgsea_analysis_prepost[["post_VACCINE"]][[j]]$output)[1]))
  }
}






fgsea_analysis_prepost_env <- list()
for(j in names(geneset_list)) {
  if(j == "CHEA"){
    size <- 5000
  } else {
    size <- 500
  }
  fgsea_analysis_prepost_env  <- fgsea_output_topT(fgsea_analysis_prepost_env ,
                             eset_contrast = fits_rv144_prepost_vaxx_env$topTable,
                             outcome = "post_VACCINE",
                             geneset_list = geneset_list,
                             geneset = j,
                             fileDir = GSEA_dir,
                             p_thr = 0.99,
                             method = "T", 
                             maxSize = size)
  if(dim(fgsea_analysis_prepost_env[["post_VACCINE"]][[j]]$output)[1] >0){
      print(c("post_VACCINE",j,
              dim(fgsea_analysis_prepost_env[["post_VACCINE"]][[j]]$output)[1]))
  }
}



fgsea_analysis_prepost_env2 <- list()
for(i in names(fits_rv144_prepost_vaxx_env$topTable)){
  
  for(j in names(geneset_list)) {
    if(j == "CHEA"){
      size <- 5000
    } else {
      size <- 500
    }
    fgsea_analysis_prepost_env2  <- fgsea_output_topT(fgsea_analysis_prepost_env2 ,
                               eset_contrast = fits_rv144_prepost_vaxx_env$topTable[[i]],
                               outcome = i,
                               geneset_list = geneset_list,
                               geneset = j,
                               fileDir = GSEA_dir,
                               p_thr = 0.99,
                               method = "T", 
                               maxSize = size)
    if(dim(fgsea_analysis_prepost_env2[[i]][[j]]$output)[1] >0){
        print(c(i,j,
                dim(fgsea_analysis_prepost_env2[[i]][[j]]$output)[1]))
    }
  }
}




saveRDS(fgsea_analysis_prepost,file = "gsea_analysis_prepost_RV144.RDS" )


prepost_CHEA_CREB_LE <-  fgsea_analysis_prepost$`post_VACCINE-pre_VACCINE`$CHEA$output %>%
                          filter(pathway == "CREB1") %>%
                          unnest(.) %>%
                          .$leadingEdge

CREB_filt_prepost_df <- exprs(eset_ave_pilot) %>%
                        as.data.frame(.) %>%
                        rownames_to_column("IlmnID") %>%
                        gather(sample, value, -IlmnID) %>%
                        inner_join(., pData(eset_ave_pilot), by = c("sample" = "Sample name")) %>%
                        filter(grepl("DMSO_3h", sample)) %>%
                        inner_join(., fData(eset_ave_pilot), by = "IlmnID") %>%
                        filter(SYMBOL %in% prepost_CHEA_CREB_LE) %>%
                        filter(treatment == "VACCINE")

expr_mat_gsva_prepost <- CREB_filt_prepost_df %>%
                        dplyr::select(sample, SYMBOL, value) %>%
                        spread(sample, value) %>%
                        column_to_rownames("SYMBOL") %>%
                        as.matrix(.)
annot_gsva_prepost <- CREB_filt_prepost_df %>%
                        dplyr::select(sample, treatment, visit) %>%
                        unique(.) %>%
                        rowid_to_column("rowid") %>%
                        dplyr::select(-rowid) %>%
                        column_to_rownames("sample")

CHEA <- getGmt("../input/genesets/CHEA-tf.gmt")
CHEA_CREB <- CHEA[names(CHEA) == "CREB1"]

gsva_prepost_CREB <- gsva(expr_mat_gsva_prepost, CHEA_CREB, method = "zscore") %>%
                      as.data.frame(.)
gsva_prepost_CREB <- gsva_prepost_CREB[,order(gsva_prepost_CREB)] %>% as.matrix(.)


prepost_hm_CREB <- pheatmap(gsva_prepost_CREB, 
                            annotation_col = annot_gsva_prepost["visit"],
                            cluster_rows = FALSE,
                            show_colnames = FALSE,
                            cellheight = 20,
                            cellwidth = 20, 
                            cluster_cols = FALSE,
                            scale = "row",
                            color =  colorRampPalette(colors = c("blue","white","red"))(500),
                            treeheight_col = 4,
                            filename = file.path(figureDir,"prepost/SLE_CREB_CHEA_prepost.pdf"),
                            height = 16,
                            width = 20, 
                            fontsize = 6)

write.csv(fgsea_analysis_prepost$`post_VACCINE-pre_VACCINE`$CHEA$output %>% 
            filter(pathway == "CREB1") %>% 
            dplyr::select(-leadingEdge),
          file = file.path(dataOutDir,"prepost_GSEA_table.csv"))


gsva_prepost_CREB_boxplot <- t(gsva_prepost_CREB) %>%
                              as.data.frame(.) %>%
                              rownames_to_column("SampleID") %>%
                              inner_join(., pData(eset_ave_pilot) %>% rownames_to_column("SampleID"), by = "SampleID" ) %>%
                              mutate(visit = ifelse(visit == "pre", "Pre-vaccination", "Post-vaccination" )) %>%
                              ggboxplot(., x = "visit", y = "CREB1", color = "visit", palette = brewer.pal(8, "Dark2")[c(5:6)],
                              add = "jitter", outlier.shape = NA) +
                              stat_compare_means(label = "p.signif", label.x = 1.5, method = "wilcox.test") +
                              xlab("Vaccination Timepoint") +
                              ylab("CREB1 Z-score")

pdf(file.path(figureDir,"prepost/SLE_CREB_CHEA_prepost_boxplot.pdf"), height = 4, width = 4)
gsva_prepost_CREB_boxplot
dev.off()


```



```{r prepost_figures}



CREB_subset <- c("CREB", "GPCR", "DARPP", "PKA", "CHEMOKINE", "CXCR[0-9]+", "CCR[0-9]+", "ATF1", "EPAC")
genesets_figs <- c("c2", "c3", "CHEA")




  for(j in genesets_figs){
      gsea_hm(fgsea_analysis_prepost, 
        contrasts = names(fgsea_analysis_prepost ),
        geneset = j,
                    pval_thr = 0.05,
                    filename  = paste("output/figures/prepost/",j,"_gsea_prepost_RV144","_CREB.pdf", sep = ""), 
                    clusterRowsGap = FALSE,
                    max_gs = 15,
                    subset = CREB_subset
                    )
    
    gsea_hm(fgsea_analysis_prepost , 
        contrasts = names(fgsea_analysis_prepost),
        geneset = j,
                    pval_thr = 0.05,
                    filename  = paste("output/figures/prepost/",j,"_gsea_prepost_RV144",".pdf", sep = ""), 
                    clusterRowsGap = FALSE,
                    max_gs = 15
                    )

}








```

```{r ledge_hm}

test <- sapply(gsea_prepost_GPCR_chemok_barplot$pathway, simplify = F , USE.NAMES = T, function(x){
      df <- gsea_prepost_GPCR_chemok_barplot %>%
              filter(pathway == x) %>%
              unnest(cols= "leadingEdge")
      ledge <- df$leadingEdge
      
      annot_df <- pData(eset_ave_pilot) %>%
                  rownames_to_column("sample") %>%
                  filter(treatment == "VACCINE") %>%
                  arrange(visit) %>%
                  column_to_rownames("sample")          
        
        
      mat <- exprs(eset_ave_pilot) %>%
              as.data.frame() %>%
              rownames_to_column("IlmnID") %>%
              inner_join(., fData_ave_pilot, by = "IlmnID") %>%
              filter(SYMBOL %in% ledge) %>%
              dplyr::select(SYMBOL, row.names(annot_df)) %>%
              column_to_rownames("SYMBOL") %>%
              as.matrix(.) %>%
              t(.) %>%
              scale(.)
      
     
              
      colorLS <- colorRampPalette(colors = c("blue", "white", "red"))(500)
      myBreaks <- seq(-max(abs(mat)), max(abs(mat)), length.out = 500)
    
      
      p <- pheatmap(t(mat), 
                            annotation_col = annot_df["visit"],
                            cluster_rows = FALSE,
                            show_colnames = FALSE,
                            scale = "none",
                            main = x,
                            cellheight = 8,
                            cellwidth = 8, 
                            color =  colorLS,
                            breaks = myBreaks,
                            cluster_cols = F,
                            height = 6,
                            width = 16,
                            fontsize = 6)
  return(p)
})



```

```{r gsva_rv144}

CREB_LE <- fgsea_analysis_titers$wk26_V1V2$CHEA$output %>%
          filter(pathway == "CREB1") %>%
          unnest(.) %>%
          .$leadingEdge

write.csv(CREB_LE, file = "output/data/CREB_wk26_ledge_RV144.csv", quote = F, row.names = F)

CREB_exprs_mat <- exprs(eset_corr_titer) %>%
                  as.data.frame(.) %>%
                  rownames_to_column("Illmn.ID") %>%
                  gather(Sample.ID, value, -Illmn.ID) %>%
                  inner_join(., fData(eset_corr_titer) %>% rownames_to_column("Illmn.ID"), by = "Illmn.ID") %>%
                  dplyr::select(SYMBOL, Sample.ID, value) %>%
                  filter(SYMBOL %in% CREB_LE) %>%
                  spread(Sample.ID, value) %>%
                  column_to_rownames("SYMBOL") %>%
                  as.matrix(.)

gsva_titers_CREB <- gsva(CREB_exprs_mat, CHEA_CREB, method = "zscore")


corr_degs <- fits_rv144$topTable %>%
              filter(adj.P.Val < 0.05) %>%
              .$SYMBOL

mart = useMart("ensembl", dataset="hsapiens_gene_ensembl")
ensembl_id <-  getBM(attributes= c("hgnc_symbol","ensembl_gene_id"),
                  filters = 'hgnc_symbol', values = corr_degs, mart = mart)

go_ids <-  getBM(attributes= c("ensembl_gene_id", "go_id", "name_1006", "namespace_1003"),
                  filters = 'ensembl_gene_id', values = ensembl_id$ensembl_gene_id, mart = mart) 

tf_go_ids <- c("GO:0003700","GO:0000130", "GO:0001071", "GO:0001130", "GO:0001131", 
                                  "GO:0001151", "GO:0001199", "GO:0001204")
tf_gene_ids <- merge(ensembl_id, go_ids, by = "ensembl_gene_id") %>%
              filter(go_id %in% tf_go_ids) %>%
              .$hgnc_symbol %>%
                  unique(.)


go_ids_immune <- read_excel(path = "../output/data/go_term_category_filters_upd.xlsx") %>%
                  filter(keep == 1)

immune_gene_ids <- merge(ensembl_id,go_ids, by  = "ensembl_gene_id") %>%
                  filter(go_id %in% go_ids_immune$go_id) %>%
                  .$hgnc_symbol %>%
                  unique(.)


corr_degs_exprs <-  exprs(eset_corr_titer) %>%
                  as.data.frame(.) %>%
                  rownames_to_column("Illmn.ID") %>%
                  gather(Sample.ID, value, -Illmn.ID) %>%
                  inner_join(., fData(eset_corr_titer) %>% rownames_to_column("Illmn.ID"), by = "Illmn.ID") %>%
                  dplyr::select(SYMBOL, Sample.ID, value) %>%
                  filter(SYMBOL %in% corr_degs) %>%
                  filter(SYMBOL %in% c(immune_gene_ids, tf_gene_ids)) %>%
                  spread(SYMBOL, value)


immport_annot <- read_excel("../input/IMMPORT_annotations.xls")
                  
  
corr_degs_exprs_immune <-  exprs(eset_corr_titer) %>%
                  as.data.frame(.) %>%
                  rownames_to_column("Illmn.ID") %>%
                  gather(Sample.ID, value, -Illmn.ID) %>%
                  inner_join(., fData(eset_corr_titer) %>% rownames_to_column("Illmn.ID"), by = "Illmn.ID") %>%
                  dplyr::select(SYMBOL, Sample.ID, value) %>%
                  filter(SYMBOL %in% corr_degs) %>%
                  filter(SYMBOL %in% immport_annot$Symbol) %>%
                  spread(SYMBOL, value)
               


CREB_corr_DEG <- gsva_titers_CREB %>%
                  as.data.frame(.) %>%
                  rownames_to_column("source") %>%
                  gather(Sample.ID, zscore, -source) %>%
                  inner_join(., corr_degs_exprs, by = "Sample.ID") %>%
                  gather(SYMBOL, expression_value, -source, -Sample.ID, -zscore) %>%
                  group_by(SYMBOL) %>%
                  do(model = cor.test(.$expression_value, .$zscore, method = "spearman")) %>%
                  tidy(., model) %>%
                  ungroup(.) %>%
                  mutate(padj = p.adjust(p.value, method = "BH")) %>%
                  filter(p.value < 0.05) %>%
                  filter(padj < 0.05) %>%
                  filter(sign(estimate) == 1) %>%
                  .$SYMBOL

CREB_corr_DEG_immune <- gsva_titers_CREB %>%
                  as.data.frame(.) %>%
                  rownames_to_column("source") %>%
                  gather(Sample.ID, zscore, -source) %>%
                  inner_join(., corr_degs_exprs_immune, by = "Sample.ID") %>%
                  gather(SYMBOL, expression_value, -source, -Sample.ID, -zscore) %>%
                  group_by(SYMBOL) %>%
                  do(model = cor.test(.$expression_value, .$zscore, method = "spearman")) %>%
                  tidy(., model) %>%
                  ungroup(.) %>%
                  mutate(padj = p.adjust(p.value, method = "BH")) %>%
                  filter(p.value < 0.05) %>%
                  filter(padj < 0.05) %>%
                  filter(sign(estimate) == 1) %>%
                  inner_join(., immport_annot, by = c("SYMBOL" = "Symbol"))
  
  
write.table(CREB_corr_DEG, file = "output/data/CREB_corr_DEGS_UP.txt", sep = ",", quote = FALSE, row.names = FALSE)

                  
write.table(CREB_corr_DEG_immune, file = "output/data/CREB_corr_DEGS_UP_immune.txt", sep = ",", quote = FALSE,
            row.names = FALSE)




```



```{r chea_overlap_titers_prepost}
overlap_list <- list("prepost" = fgsea_analysis_prepost$`post_VACCINE-pre_VACCINE`$CHEA$output,
      "titers" = fgsea_analysis_titers$wk26_V1V2$CHEA$output)

overlap_df <- do.call("rbind", sapply(names(overlap_list), simplify = F, USE.NAMES = T, function(x){
    df <- overlap_list[[x]] %>%
            filter(pval < 0.05) %>%
            filter(NES > 0) %>%
            mutate(condition = x) %>%
            dplyr::select(-leadingEdge)
    return(df)
})) %>%
  group_by(pathway) %>%
  mutate(n_conditions = n_distinct(condition)) %>%
  ungroup(.) %>%
  filter(n_conditions == 2) %>%
  .$pathway %>%
  unique()

write(overlap_df, file = "output/data/prepost_titer_overlapping_CHEA.txt", sep = "\n")

```



Compare CREB z-score to v1v2 to case control as logistic regression.
Also spit z-score into tertiles, and run it pairwise.

```{r CREB cytok}

# CREB_filt_HIV_pos_df <- exprs(eset_ave) %>%
#                         as.data.frame(.) %>%
#                         rownames_to_column("IlmnID") %>%
#                         gather(sample, value, -IlmnID) %>%
#                         inner_join(., pData(eset_ave), by = c("sample" = "Sample name")) %>%
#                         filter(stimulation == "DMSO" & treatment == "VACCINE") %>%
#                         inner_join(., fData(eset_ave), by = "IlmnID") %>%
#                         filter(SYMBOL %in% HIV_pos_CHEA_CREB_LE)
# 
# expr_mat_gsva_HIV_pos <- CREB_filt_HIV_pos_df %>%
#                         dplyr::select(sample, SYMBOL, value) %>%
#                         spread(sample, value) %>%
#                         column_to_rownames("SYMBOL") %>%
#                         as.matrix(.)
# 
# annot_gsva_HIV_pos <- CREB_filt_HIV_pos_df %>%
#                         dplyr::select(sample, `HIV infection` ) %>%
#                         unique(.) %>%
#                         rowid_to_column("rowid") %>%
#                         dplyr::select(-rowid) %>%
#                         #unique(.) %>%
#                         column_to_rownames("sample")
# 
# 
##extract gender from clinicalAnnotation in 20131007_RV144.preprocessing
pData_clinical <- clinicalAnnotation %>%
                mutate(time_to_infect = time_to_infect - time_to_wk26) %>%
                dplyr::select(pin, dem_sex, BRA_risk, time_to_infect, infect ) %>%
                mutate(donor = as.character(pin)) %>%
                unique(.)

logit_downsampling_id <- pData(eset_ave) %>%
                            rownames_to_column("SampleID") %>%
                            filter(SampleID %in% colnames(gsva_HIV_pos_CREB)) %>%
                            group_by(`HIV infection`) %>%
                            mutate(n = n_distinct(SampleID)) %>%
                            ungroup() %>%
                            mutate(min_n = min(n)) %>%
                            group_by(`HIV infection`) %>%
                            sample_n(., size = min_n) %>%
                            ungroup()

print(logit_downsampling_id$SampleID)
gsva_HIV_pos_CREB_logit_prep <- t(gsva_HIV_pos_CREB) %>%
                              as.data.frame(.) %>%
                              rownames_to_column("SampleID") %>%
                              inner_join(., pData(eset_ave) %>% rownames_to_column("SampleID"), by = "SampleID" ) %>%
                              mutate(`HIV infection` = ifelse(`HIV infection` == "Yes", 1, 0 )) %>%
                              dplyr::rename(HIV_infection  = `HIV infection`) %>%
                              mutate(donor = as.character(donor)) %>%
                              inner_join(., pData_clinical, by ="donor") %>%
                              mutate(dem_sex = factor(dem_sex)) %>%
                              mutate(CREB_tertiles = ntile(CREB1, n = 3)) %>%
                              mutate(CREB_sub = ifelse(CREB_tertiles == 1, "low", 
                                                       ifelse(CREB_tertiles == 2, "medium", "high"))) %>%
                              mutate(CREB_sub  = factor(CREB_sub, levels = c("low", "medium", "high"))) %>%
                              mutate(censored = ifelse(infect == "Yes", 1, 0)) %>%
                              
                              mutate(time_to_infect = (time_to_infect /365) *12)
                
#HIV_acq_downsampling <- do.call("rbind",lapply(c(1:100), function(x){
HIV_acq_downsampling <- list()

for (i in c(1:100)){
  set.seed(seed = i)
  logit_downsampling_id <- pData(eset_ave) %>%
                            rownames_to_column("SampleID") %>%
                            filter(SampleID %in% colnames(gsva_HIV_pos_CREB)) %>%
                            group_by(`HIV infection`) %>%
                            mutate(n = n_distinct(SampleID)) %>%
                            ungroup() %>%
                            mutate(min_n = min(n)) %>%
                            filter(min_n != n) #%>%
  if(i <= unique(logit_downsampling_id$min_n)){
    HIV_acq_downsampling[[i]] <- logit_downsampling_id %>%
                            group_by(`HIV infection`) %>%
                            sample_n(., size = min_n) %>%
                            ungroup() %>%
                            inner_join(., gsva_HIV_pos_CREB_logit_prep, by = "SampleID") %>%
                            group_by(HIV_infection) %>%
                            summarize(mean= mean(CREB1, na.rm = T)) %>%
                            mutate(iteration = i) %>%
                            dplyr::rename(CREB1 = "mean") %>%
                            dplyr::rename(SampleID = "iteration") %>%
                            mutate(SampleID = as.character(SampleID))
  }
}
HIV_acq_down <- gsva_HIV_pos_CREB_logit_prep %>%
                  filter(!HIV_infection %in% HIV_acq_downsampling[[1]]$HIV_infection ) %>%
                  dplyr::select(HIV_infection, CREB1, SampleID) %>%
                  bind_rows(do.call('rbind', HIV_acq_downsampling)) %>%
                  ggboxplot(., x = "HIV_infection", y = "CREB1")
  
  
  
  # rv144_logit_CREB <- glm(HIV_infection~dem_sex+BRA_risk + CREB1, 
  #                       data = gsva_HIV_pos_CREB_logit_prep %>%
  #                                 filter(SampleID %in%  logit_downsampling_id$SampleID ), 
  #                       family = "binomial")

})

})) %>%
  ggboxplot(., x = "HIV_infection", y = "mean")
              





CREB_HIV_pos <-  ggboxplot(gsva_HIV_pos_CREB_logit_prep  %>%
                                  filter(SampleID %in%  logit_downsampling_id$SampleID ), 
                        x = "HIV_infection", y = "CREB1", color = "HIV_infection", 
                                        palette = c("dodgerblue4","darkred"),
                              add = "jitter", outlier.shape = NA) +
                              xlab("HIV infection") +
                              ylab("CREB1 Z-score")




rv144_logit_CREB <- glm(HIV_infection~dem_sex+BRA_risk + CREB1, 
                        data = gsva_HIV_pos_CREB_logit_prep %>%
                                  filter(SampleID %in%  logit_downsampling_id$SampleID ), 
                        family = "binomial")

rv144_logit_CREB_sub <- sapply(c("low_vs_high", "medium_vs_high", "low_vs_medium"), simplify = F, USE.NAMES = T, function(x){
  groups <- str_split(x, pattern = "_vs_")[[1]]
  print(groups)
   df <- gsva_HIV_pos_CREB_logit_prep %>%
          filter(CREB_sub %in% groups) %>%
          mutate(contrast = ifelse(CREB_sub == groups[1], "0", "1")) 
   model <- glm(HIV_infection~dem_sex + BRA_risk + contrast,  data = df, family = "binomial")
   return(tidy(model))
})


gsva_HIV_pos_CREB_surv <- gsva_HIV_pos_CREB_logit_prep 
surv_object <- survival::Surv(time = gsva_HIV_pos_CREB_surv$time_to_infect, event = gsva_HIV_pos_CREB_surv$censored) 
fit1 <- survival::survfit(surv_object ~ CREB_sub, data = gsva_HIV_pos_CREB_surv)

surv_CREB_curve <- ggsurvplot(fit1, data =gsva_HIV_pos_CREB_surv, pval = TRUE, fun = "event",
          # risk.table = T,
           break.x.by = 6, 
           break.y.by = 0.1,
           ylim = c(0, 0.4),
           xlab = "Months after Week 26",
           ylab = "Cumulative %\n of infected patients",
          legend.labs = c("Low", "Medium", "High"),
          legend.title = "CREB1 subgroups (tertiles)") +
        theme_survminer(base_size = 8) +
        theme(test = element_text(family = "Arial")) %>%
        guides(colour = guide_legend(nrow = 2))
        ggsave("output/figures/survival_curve_RV144.pdf", device = "pdf", height =4, width =4 , units = "in")

#surv_pw <- pairwise_survdiff(Surv(time_to_infect, event =  censored) ~ CREB_sub, data = gsva_HIV_pos_CREB_surv)

#write.csv(tidy(surv_pw), file = "output/data/survival_pairwise.csv")
pdf("output/figures/survival_curve_RV144.pdf", width = 4.5, height = 4)
surv_CREB_curve
dev.off()

# KM_CREB_strat <- pData(eset_ALVAC_titer) %>%
#                    rownames_to_column("sample_id") %>%
#                    mutate(Group = ifelse(`rV2_E543-3_Post-_Vax` > 0, 1, 0)) %>%
#                    mutate(right_c = ifelse(Challenge_no == 11, 0, 1)) %>%
#                    mutate(Group = factor(Group, levels = c(0, 1), labels = c("Neg", "Pos"))) %>%
#                    inner_join(., gsva_CREB_strat, by = "sample_id")
# 
# 
# as_tibble(test_KM)
# library(survival)
# # surv_object <- survival::Surv(time = test_KM$Challenge_no, event = test_KM$right_c) 
# surv_object <- survival::Surv(time = KM_CREB_strat$Challenge_no, event = KM_CREB_strat$right_c) 
# 
# 
# fit1 <- survival::survfit(surv_object ~ extreme_split, data = KM_CREB_strat)
# 
# library(survminer)
# ggsurvplot(fit1, data =KM_CREB_strat, pval = TRUE, 
#            break.x.by = 1, 
#            break.y.by = 0.1,
#            xlab = "Number of IR challenges",
#            ylab = "%infection-free probability")



```


```{r chemok_genes_acquisition}
chemokine_genes <-  read_excel("../input/IMMPORT_annotations.xls")  %>% 
                          filter(grepl("Chemok", Category)) %>%
                          .$Symbol


fits_rv144_prepost_vaxx_env$topTable$post_VACCINE_3h %>% 
   filter(SYMBOL %in% chemokine_genes) %>%
   filter(t > 0) %>%
   filter(P.Value < 0.05)
fits_rv144_prepost_vaxx_env$topTable$post_VACCINE_15h %>% 
   filter(SYMBOL %in% chemokine_genes) %>%
   filter(t > 0) %>%
   filter(P.Value < 0.05)


fits_rv144_hiv_pos$topTable %>% 
   filter(SYMBOL %in% chemokine_genes) %>%
   filter(t > 0) %>%
   filter(P.Value < 0.05)


```



```{r chemok_survival}

p162_chemokine_sig <- read.csv("../p162/output/data/p162_chemokine_GPCR_signaling.csv")

p162_functional_sig <- read.csv("../p162/output/data/P162_functional_adjuvant_pathways.csv")


chemok_hiv_pos_ledge_temp_post <- do.call("rbind", lapply(c("c2","c5", "c7"), function(x){
  #df <-  fgsea_analysis_prepost$post_VACCINE[[x]]$output %>%
  out <- do.call("rbind", lapply(names(fgsea_analysis_prepost_env2), function(y){
    df <-  fgsea_analysis_prepost_env2[[y]][[x]]$output %>%
          #filter(grepl("CXCR|CCR|CX3CR|MIGRATION|CHEMOTAXIS|MIP|FRACTALK|CHEMOK",pathway)) %>%
          filter(pathway %in% p162_functional_sig$functional_pathway) %>%
          filter(pval < 0.05)  %>%
          filter(NES > 0) %>%
          mutate(collection = x)
          return(df)
  }))
  return(out)
})) 



chemok_hiv_pos_ledge_temp <- do.call("rbind", lapply(c("c2","c5", "c7"), function(x){
  df <-  fgsea_analysis_hiv_pos$`HIV_Pos_VACCINE-HIV_Neg_VACCINE`[[x]]$output %>%
    #filter(grepl("CXCR|CCR|CX3CR|MIGRATION|CHEMOTAXIS|MIP|FRACTALK|CHEMOK",pathway)) %>%
    #filter(pathway %in% p162_chemokine_sig$pathway) %>%
    filter(pathway %in% chemok_hiv_pos_ledge_temp_post$pathway) %>%
    filter(pval < 0.05)  %>%
    filter(NES < 0) %>%
    mutate(collection = x)
    return(df)
})) %>% split(., f = .$pathway)

# 
# chemok_hiv_pos_ledge_temp2 <- do.call("rbind", lapply(c("c2","c5", "c7"), function(x){
#   df <-  fgsea_analysis_hiv_pos$`HIV_Pos_VACCINE-HIV_Neg_VACCINE`[[x]]$output %>%
#     filter(grepl("CXCR|CCR|CX3CR|MIGRATION|CHEMOTAXIS|MIP|FRACTALK|CHEMOK",pathway)) %>%
#     #filter(pathway %in% p162_functional_sig$functional_pathway) %>%
#     #filter(pathway %in% p162_chemokine_sig$pathway) %>%
#     #filter(pathway %in% chemok_hiv_pos_ledge_temp_post$pathway) %>%
#     filter(pval < 0.05)  %>%
#     filter(NES < 0) %>%
#     mutate(collection = x)
#     return(df)
# })) %>% split(., f = .$pathway)




chemok_hiv_pos_ledge <- sapply(names(chemok_hiv_pos_ledge_temp), USE.NAMES = T, simplify = F, function(x){
  ledge <- chemok_hiv_pos_ledge_temp[[x]] %>%
            unnest(cols = "leadingEdge") %>%
            .$leadingEdge
  return(ledge)
})


# leadingEdge_hiv_corr <- do.call("rbind", lapply(names(chemok_hiv_pos_ledge_temp), function(x){
#   df <- chemok_hiv_pos_ledge_temp[[x]] %>%
#       unnest(cols = "leadingEdge") %>%
#       mutate(ledge = leadingEdge) %>%
#       mutate(leadingEdge = paste(ledge, collapse = ", ")) %>%
#       dplyr::select(pathway, leadingEdge) %>%
#       unique() 
#   return(df)
# }))
# 
# write.csv(leadingEdge_hiv_corr, file = "output/data/functional_pathways_hiv_acquisition_rv144.csv")

p162_ledge <- read.csv("../p162/output/data/mf59_alum_functional_ledge.csv")  %>%
                separate_rows(leadingEdge, sep = "; ") %>%
                split(., f = .$ind)



p162_intersect <- bind_rows(lapply(names(chemok_hiv_pos_ledge), function(x){
                           ledge <- intersect(p162_ledge[[x]]$leadingEdge, chemok_hiv_pos_ledge[[x]])
                           frac_alum_in_hiv_acq <- length(ledge) / length(chemok_hiv_pos_ledge[[x]])
                           frac_hiv_in_alum <- length(ledge)/ length(p162_ledge[[x]]$leadingEdge)
                           df <- data.frame("pathway" = x, 
                                            "leadingEdge" = paste(ledge, collapse = "; "),
                                            "freq_in_total_hiv" = frac_alum_in_hiv_acq,
                                            "freq_in_total_alum" = frac_hiv_in_alum)
                            return(df)
                         }))

chemok_filt_HIV_pos_df <- sapply(names(chemok_hiv_pos_ledge), simplify = F, USE.NAMES = T, function(x){
        #ledge <- chemok_hiv_pos_ledge[[x]]
        ledge <- p162_intersect %>% 
                  filter(pathway == x) %>% 
                  separate_rows(leadingEdge, sep = "; ") %>%
                        .$leadingEdge
        #ledge <- list("p162" = p162_ledge[[x]]$leadingEdge, "rv144" =  chemok_hiv_pos_ledge[[x]])
        #return(ledge)
        df <-        exprs(eset_ave) %>%
                        as.data.frame(.) %>%
                        rownames_to_column("IlmnID") %>%
                        gather(sample, value, -IlmnID) %>%
                        inner_join(., pData(eset_ave), by = c("sample" = "Sample name")) %>%
                        filter(stimulation == "DMSO" & treatment == "VACCINE") %>%
                        inner_join(., fData(eset_ave), by = "IlmnID") %>%
                        filter(SYMBOL %in% ledge)
        return(df)
})
                                  



expr_mat_gsva_HIV_pos_chemok <- sapply(names(chemok_filt_HIV_pos_df), simplify = F, USE.NAMES = T, function(x){
  exprs  <- chemok_filt_HIV_pos_df[[x]] %>%
                        dplyr::select(sample, SYMBOL, value) %>%
                        spread(sample, value) %>%
                        column_to_rownames("SYMBOL") %>%
                        as.matrix(.)
  return(exprs)
})
  



gsva_HIV_pos_chemok <- sapply(names(expr_mat_gsva_HIV_pos_chemok), simplify = F, USE.NAMES = T, function(x){
  collection <- chemok_hiv_pos_ledge_temp[[x]]$collection
  coll <- getGmt(geneset_list[[collection]])
  gs <- coll[names(coll) == x]
  gsva <-  as.data.frame(gsva(expr_mat_gsva_HIV_pos_chemok[[x]], gs, method = "zscore"))
  gsva <- gsva[,order(gsva)] %>% as.matrix(.)
 
  return(gsva)
})
  

gsva_HIV_pos_chemok_logit_prep <- sapply(names(gsva_HIV_pos_chemok), simplify = F, USE.NAMES = T, function(x){
        df <- t(gsva_HIV_pos_chemok[[x]]) %>%
              as.data.frame(.) %>%
              rownames_to_column("SampleID") %>%
              inner_join(., pData(eset_ave) %>% rownames_to_column("SampleID"), by = "SampleID" ) %>%
              mutate(`HIV infection` = ifelse(`HIV infection` == "Yes", 1, 0 )) %>%
              dplyr::rename(HIV_infection  = `HIV infection`) %>%
              mutate(Acquisition = ifelse(HIV_infection == 1, "HIV Positive", "HIV Negative")) %>%
              mutate(Acquisition = factor(Acquisition , levels = c("HIV Negative", "HIV Positive"))) %>%
              mutate(donor = as.character(donor)) %>%
              inner_join(., pData_clinical, by ="donor") %>%
              mutate(dem_sex = factor(dem_sex)) %>%
              rename(pathway = x) %>%
              mutate(tertiles = ntile(pathway, n = 3)) %>%
              mutate(tertile_sub = ifelse(tertiles == 1, "low", 
                                       ifelse(tertiles == 2, "medium", "high"))) %>%
              mutate(tertile_sub  = factor(tertile_sub, levels = c("low", "medium", "high"))) %>%
              mutate(censored = ifelse(infect == "Yes", 1, 0)) %>%
              mutate(time_to_infect = (time_to_infect /365) *12)
                              
    return(df)
})
  
rv144_logit_chemok <-  sapply(names(gsva_HIV_pos_chemok_logit_prep), simplify = F, USE.NAMES = T, function(x){
  #rv144_logit_chemok_sub <- sapply(c("low_vs_high", "medium_vs_high", "low_vs_medium"), simplify = F,
   #                                USE.NAMES = T, function(y){
    #groups <- str_split(y, pattern = "_vs_")[[1]]
    #print(groups)
   df <- gsva_HIV_pos_chemok_logit_prep[[x]] %>%
          #filter(tertile_sub %in% groups) %>%
          mutate(contrast = ifelse(infect== "No", "0", "1")) 
   #return(df)
   model <- glm(HIV_infection~dem_sex + BRA_risk + pathway,  data = df, family = "binomial")
   return(tidy(model))
  #})
})

# rv144_chemok_boxplots <- sapply(names(gsva_HIV_pos_chemok_logit_prep), simplify = F, USE.NAMES = T, function(k){
# 
#        p <-     ggboxplot(gsva_HIV_pos_chemok_logit_prep[[k]], x = "Acquisition", y = "pathway", color = "Acquisition",
#                                         palette = c("dodgerblue4","darkred"),
#                               add = "jitter", outlier.shape = NA) +
#                               #stat_compare_means(label = "p.signif", label.x = 1.5, method = "wilcox.test") +
#                               xlab("HIV infection") +
#                               ylab("Z-score") +  
#                               ggtitle(k)
#     return(p)
#   
# })




gsva_chemok_consolidated <- do.call("rbind", lapply(gsva_HIV_pos_chemok, function(x){
  df <- x %>%
        as.data.frame() %>%
        rownames_to_column("pathway") %>%
        gather(sample, zscore, -pathway) 
  return(df)
})) %>%
  remove_rownames() %>%
  spread(pathway, zscore) %>%
  column_to_rownames("sample") %>%
  as.matrix(.)


gsva_CREB_chemok_corr <- gsva_HIV_pos_CREB %>%
                          as.data.frame() %>%
                          rownames_to_column("CREB") %>%
                          gather(SampleID, CREB_zscore, -CREB) %>%
                          inner_join(., as.data.frame(gsva_chemok_consolidated) %>% rownames_to_column("SampleID"),
                                     by = "SampleID") %>%
                          gather(pathway, zscore, -SampleID, -CREB, -CREB_zscore) %>%
                          group_by(pathway) %>%
                          do(model = cor.test(.$CREB_zscore, .$zscore, method = "spearman"))  %>%
                          tidy(., model) %>%
                          filter(p.value < 0.05) %>%
                          arrange(desc(estimate))






# hm_annot_hiv_acquisition <- pData(eset_ave) %>% 
#               rownames_to_column("SampleID") %>%
#               mutate(`HIV infection` = ifelse(`HIV infection` == "Yes", 1, 0 )) %>%
#               dplyr::rename(HIV_infection  = `HIV infection`) %>%
#               mutate(Acquisition = ifelse(HIV_infection == 1, "HIV Positive", "HIV Negative")) %>%
#               mutate(donor = as.character(donor)) %>%
#               inner_join(., pData_clinical, by ="donor") %>%
#               mutate(dem_sex = factor(dem_sex)) %>%
#               filter(`Sample name` %in% row.names(gsva_chemok_consolidated)) %>%
#               column_to_rownames("SampleID")
#              


# chemok_hm <- pheatmap(mat = t(gsva_chemok_consolidated),
#                       scale = "row",
#                       clustering_method = "ward.D2",
#                       color = colorRampPalette(colors = c("blue", "white", "red"))(500),
#                       show_colnames = F,
#                       cellheight = 10,
#                       cellwidth = 1.5,
#                       fontsize = 9,
#                       annotation_col = hm_annot_hiv_acquisition["Acquisition"])
# pdf("output/figures/p162_functional_genesetss_vs_acquisition.pdf", width = 9)
# chemok_hm
# dev.off()
# 
# 




leadingEdge_hiv_corr <-   p162_intersect %>%
                          #do.call("rbind", chemok_hiv_pos_ledge_temp)   %>%
                          #remove_rownames() %>%
                          # unnest(cols = "leadingEdge") %>%
                          # mutate(ledge = leadingEdge) %>%
                          # group_by(pathway) %>%
                          # mutate(leadingEdge = paste(ledge, collapse = ", ")) %>%
                          # ungroup() %>%
                          mutate(new_name = "") %>%
                          dplyr::select(pathway, new_name, leadingEdge) %>%
                          filter(pathway %in% gsva_CREB_chemok_corr$pathway) %>%
                          unique() 

writexl::write_xlsx(leadingEdge_hiv_corr, "output/data/leadingEdge_hiv_acquisition_genesets.xlsx")

leadingEdge_hiv_corr_upd <- read_excel("output/data/leadingEdge_hiv_acquisition_genesets_ANNOT2.xlsx") %>%
                              mutate(new_name = ifelse(is.na(new_name), pathway, new_name)) %>%
                              filter(new_name != "-") 



encode <- getGmt("../input/genesets/ENCODE-tf.gmt") 
encode_CREB_genes <- geneIds(encode[names(encode) == "CREB1"])[[1]]
transfac <- getGmt("../input/genesets/TRANSFAC.gmt")
transfac_CREB_genes <- geneIds(transfac[names(transfac) == "CREB1"])[[1]]
jasper <- getGmt("../input/genesets/JASPER-tf.gmt")
jasper_CREB_genes <- geneIds(jasper[names(jasper) == "CREB1"])[[1]]   
putative_CREB <- getGmt("../input/genesets/putative_CREB1_targets.gmt")


ledge_hm_chemok_hiv_pos <- sapply(leadingEdge_hiv_corr_upd$pathway, simplify = F, USE.NAMES = T, function(x){
  library(RColorBrewer)
      name <- leadingEdge_hiv_corr_upd %>% filter(pathway == x)  %>% .$new_name
      mat <- expr_mat_gsva_HIV_pos_chemok[[x]] 
      annot_hm <- pData(eset_ave) %>%
                  rownames_to_column("SampleID") %>%
                  filter(SampleID %in% colnames(mat)) %>%
                  dplyr::rename(HIV_infection  = `HIV infection`) %>%
                  mutate(Acquisition = ifelse(HIV_infection == "Yes", "HIV Positive", "HIV Negative")) %>%
                  arrange(Acquisition) %>%
                  column_to_rownames("SampleID") 
      #return(mat)
      
      
      # ntile_mat <- mat %>%
      #               as.data.frame() %>%
      #               rownames_to_column("Gene") %>%
      #               gather(sample, value, -Gene) %>%
      #               mutate(quantile = ntile(value, n = 1000)) %>%
      #               dplyr::filter(quantile >= 5 ) %>%
      #               dplyr::filter(quantile <= 995)
      
      scaled_mat <- mat %>% 
                    as.data.frame() %>%
                    rownames_to_column("Gene") %>%
                    gather(sample, value, -Gene) %>%
                    group_by(Gene) %>%
                    mutate(quantile = ntile(value, n = 500)) %>%
                    mutate(scaled_quant = scale(quantile)) %>%
                    ungroup() %>%
                    group_by(sample) %>%
                    mutate(mean_sample = mean(scaled_quant)) %>%
                    ungroup() 
      order_samples <- scaled_mat %>%
                        inner_join(., annot_hm %>% rownames_to_column("sample"), by  ="sample") %>%
                        dplyr::select(sample, Acquisition, mean_sample) %>%
                        unique() %>%
                        arrange(Acquisition, desc(mean_sample))
      
      mat <- scaled_mat %>%
                    dplyr::select(Gene, sample, scaled_quant) %>%
                    spread(sample, scaled_quant) %>%
                    column_to_rownames("Gene") %>%
                    as.matrix(.)
      #return(mat)
      mat <- mat[,order_samples$sample]
      # mat <- t(scale(t(mat)))
                    
      #return(mat)
 
      myBreaks <- c(seq(min(mat, na.rm = T),0, length.out = 200)[c(1:199)], seq(0, max(mat, na.rm = T), length.out = 201))
      #myBreaks <- seq(0, max(mat, na.rm = T), length.out = 500)
      
      #myBreaks <- c(seq(min(ntile_mat$value),0, length.out = 250)[c(1:249)], seq(0, max(ntile_mat$value), length.out = 251))
      colorLS <- colorRampPalette(colors = c("blue", "white", "red"))(500)
      colorLS <- colorLS[c(50:450)]
      
      #return(min(mat))
      #return(min(myBreaks))
      #myBreaks_upd <- rev(seq(min(myBreaks) ,  min(mat), by = sqrt(myBreaks[1]^2-myBreaks[2]^2)))
      #return(myBreaks_upd)
      creb_target_colors <- brewer.pal(n = 3, name = "Dark2")
      
      annot_colors <- list("CREB Target" = c("Direct Target" = creb_target_colors[1], 
                                             "Putative Target" = creb_target_colors[2], "--" = "gray"),
                           "Acquisition" = c("HIV Negative" = "dodgerblue4", "HIV Positive" = "darkred"))

      gene_annot <- mat %>% as.data.frame() %>%
                rownames_to_column("Gene") %>%
                mutate(`CREB Target` = ifelse(Gene %in% c(encode_CREB_genes, geneIds(CHEA_CREB)$CREB1),
                                              "Direct Target", ifelse(Gene %in% c(transfac_CREB_genes, jasper_CREB_genes,
                                                                                  geneIds(putative_CREB)[[1]]), 
                                                                      "Putative Target", "--" )))  %>%
                dplyr::select(Gene, `CREB Target`)  %>%
                column_to_rownames("Gene")
      
      
      p <- pheatmap(mat = mat,
                    show_colnames = F,
                    scale = "none",
                    color = colorLS,
                    clustering_method = "ward.D2",
                    annotation_row = gene_annot["CREB Target"],
                    cellwidth = 2.5,
                    cellheight = 15,
                    fontsize = 12,
                    cluster_cols = F,
                    cluster_rows = T,
                    annotation_col = annot_hm["Acquisition"],
                    filename = paste("output/figures/functional_leadingEdge_hm/HIV_acquisition_ledge_heatmap_", name, ".pdf"),
                    main = paste(name, "\n(", x, ")", sep = ""),
                    breaks = myBreaks,
                    annotation_colors = annot_colors,
                    annotation_names_row = F,
                    height = 12,
                    width = 12)
      return(p)
})


chemok_NES_barplot_df <- do.call("rbind", chemok_hiv_pos_ledge_temp) %>%
                        arrange(desc(NES)) %>%
                       # mutate(NES = NES * -1) %>% #preferrence form jeff
  
                        inner_join(., leadingEdge_hiv_corr_upd, by = "pathway")
                        
chemok_NES_barplot <- ggplot(chemok_NES_barplot_df, aes(x = reorder(new_name, -NES), y = NES, fill = NES)) + 
                          geom_bar(stat='identity', width=0.6, position = "identity") + 
                          theme_bw() +
                           xlab("Pathway") + 
                          ylab("NES (Normalized Enrichment Score)") + 
                          theme(axis.title = element_text(family = "Times", face="bold", size=12)) +
                           theme(axis.text = element_text(family = "Times", face="bold", size=8)) +
                          geom_hline(yintercept=0, color = "gray", size=0.5) +
                          scale_fill_gradientn(colours = colorRampPalette(colors = c("blue", "white", "red"))(500),
                                               limits = c(-max(abs(chemok_NES_barplot_df$NES)), 
                                                          max(abs(chemok_NES_barplot_df$NES)))) +
                          theme(text = element_text(size = 12),
                                axis.text = element_text(size = 12),
                                axis.title = element_text(size = 14, face = 'bold')) + 
                          #ggtitle("Immune related genesets vs HIV Acquisition")  + 
                          coord_flip() 


# pdf("output/figures/GSEA_chemokine_barplot_vs_HIV_aqcuisition_RV144.pdf", height = 2.5, width = 6.5)
pdf("output/figures/GSEA_immune_function_barplot_vs_HIV_aqcuisition_RV144.pdf", height = 5, width = 9)
chemok_NES_barplot
dev.off()




gsva_HIV_pos_chemok_logit_prep_filt <- gsva_HIV_pos_chemok_logit_prep[names(gsva_HIV_pos_chemok_logit_prep) %in%
                                                                        gsva_CREB_chemok_corr$pathway]

gsva_HIV_pos_chemok_logit_prep_filt <-  gsva_HIV_pos_chemok_logit_prep_filt[names(gsva_HIV_pos_chemok_logit_prep_filt) %in% 
                                                                              leadingEdge_hiv_corr_upd$pathway]


rv144_chemok_boxplots <- sapply(names(gsva_HIV_pos_chemok_logit_prep_filt), simplify = F, USE.NAMES = T, function(k){
  
      annot <- leadingEdge_hiv_corr_upd %>%
                  filter(pathway == k) %>%
                  .$new_name
  
       p <-     ggboxplot(gsva_HIV_pos_chemok_logit_prep_filt[[k]] , x = "Acquisition", y = "pathway", color = "Acquisition",
                                        palette = c("dodgerblue4","darkred"),
                              add = "jitter", outlier.shape = NA) +
                              #stat_compare_means(label = "p.signif", label.x = 1.5, method = "wilcox.test") +
                              xlab("HIV infection") +
                              ylab("Z-score") +  
                              ggtitle(annot) +
                              theme(title = element_text(size = 10, face = "bold"))
    return(p)
  
})


pdf("output/figures/RV144_functional_genesets_logit_boxplots.pdf")
rv144_chemok_boxplots
dev.off()



rv144_chemok_surv <- sapply(names(gsva_HIV_pos_chemok_logit_prep_filt), simplify = F, USE.NAMES = T, function(k){
  gsva_surv <- gsva_HIV_pos_chemok_logit_prep_filt[[k]]
  surv_object <- survival::Surv(time = gsva_surv$time_to_infect, event = gsva_surv$censored) 
  fit1 <- survival::survfit(surv_object ~ tertile_sub, data = gsva_surv)
  library(survminer)
  library(survival)
  
  annot <- leadingEdge_hiv_corr_upd %>%
                  filter(pathway == k) %>%
                  .$new_name
  
  surv_pw <- pairwise_survdiff(Surv(time_to_infect, event =  censored) ~ tertile_sub, data = gsva_surv)
  surv_pw2 <- surv_pw$p.value %>% as.data.frame() %>% rownames_to_column("group1") %>%
              gather(group2, p.value, -group1)  %>%
              filter(group1 %in% c("high", "low")) %>%
              filter(group2 %in% c("high", "low")) %>%
              .$p.value
  
  surv_curve <- ggsurvplot(fit1, data =gsva_surv, fun = "event",
          # risk.table = T,
            pval = signif(surv_pw2, digits = 2),
           break.x.by = 6, 
           break.y.by = 0.1,
           ylim = c(0, 0.4),
           xlab = "Months after Week 26",
           ylab = "Cumulative frequency\n of infected patients",
          legend.labs = c("Low", "Medium", "High"),
          legend.title = "Tertiles",
          title = annot, 
          font.title = c(6, "bold")) +
        theme_survminer(base_size = 8, font.main = c(8, "bold", "black") ) +
        theme(test = element_text(family = "Arial")) %>%
        guides(colour = guide_legend(nrow = 2))  +
        ggsave(paste("output/figures/", annot, "_survival_curve_RV144.pdf", sep = ""), device = "pdf", 
               height =4, width =5 , units = "in")
 
  return(surv_curve)

})


pdf("output/figures/RV144_functional_genesets_survival_curves.pdf", width = 4, height =4)
rv144_chemok_surv
dev.off()



```
```{r cytok_tertiles}

study36_cytok_net <- readLines("input/study36_chemokine_network_fig2A.txt")

titer_topTables_cytok_s36 <- do.call("rbind", lapply(list.files("../data_tables/contrasts/Study36", pattern = "V1V2", full.names = T), function(x){

            df <- read_tsv(x) %>%
                filter(BROAD.Gene.Symbol %in% study36_cytok_net) %>%
                filter(P.Value <0.05) %>%
                mutate(file = x) 
  
})) %>%
  group_by(BROAD.Gene.Symbol) %>%
  mutate(n_pos = sum(logFC > 0),
         n_neg = sum(logFC <0)) %>%
  ungroup() %>%
  dplyr::select(BROAD.Gene.Symbol, n_pos, n_neg) %>%
  unique() %>%
  mutate(direction = ifelse(n_pos >= n_neg, "POS", "NEG"))







study36_cytok_gs <- GeneSetCollection(list(GeneSet(setName = "Study36_Chemokine_genemania_POS",  
                                                   geneIds = unique(titer_topTables_cytok_s36[titer_topTables_cytok_s36$direction == "POS",]$BROAD.Gene.Symbol)),
                                           GeneSet(setName = "Study36_Chemokine_genemania_NEG",  
                                                   geneIds = unique(titer_topTables_cytok_s36[titer_topTables_cytok_s36$direction == "NEG",]$BROAD.Gene.Symbol))))




chemok_study36_filt_HIV_pos_df <- sapply(names(study36_cytok_gs), simplify = F, USE.NAMES = T, function(x){
          df <-           exprs(eset_ave) %>%
                        as.data.frame(.) %>%
                        rownames_to_column("IlmnID") %>%
                        gather(sample, value, -IlmnID) %>%
                        inner_join(., pData(eset_ave), by = c("sample" = "Sample name")) %>%
                        filter(stimulation == "DMSO" & treatment == "VACCINE") %>%
                        inner_join(., fData(eset_ave), by = "IlmnID") %>%
                          filter(SYMBOL %in% geneIds(study36_cytok_gs[names(study36_cytok_gs) == x])[[1]])
  
  
})

expr_mat_gsva_HIV_pos_chemok_s36 <- sapply(names(chemok_study36_filt_HIV_pos_df), simplify = F, USE.NAMES = T, function(x){
  out <- chemok_study36_filt_HIV_pos_df[[x]] %>%
                        dplyr::select(sample, SYMBOL, value) %>%
                        spread(sample, value) %>%
                        column_to_rownames("SYMBOL") %>%
                        as.matrix(.)
  
  
})
  

annot_gsva_HIV_pos_chemonk_s36 <- sapply(names(chemok_study36_filt_HIV_pos_df), simplify = F, USE.NAMES = T, function(x){
  df <- chemok_study36_filt_HIV_pos_df[[x]] %>%
                        dplyr::select(sample, `HIV infection` ) %>%
                        unique(.) %>%
                        rowid_to_column("rowid") %>%
                        dplyr::select(-rowid) %>%
                        #unique(.) %>%
                        column_to_rownames("sample")
  
}) 
                        


gsva_HIV_pos_chemok_s36 <- sapply(names(expr_mat_gsva_HIV_pos_chemok_s36), simplify = F, USE.NAMES = T, function(x){
  gs <- study36_cytok_gs[names(study36_cytok_gs) == x]
  gsva <- as.data.frame(gsva(expr_mat_gsva_HIV_pos_chemok_s36[[x]], gs, method = "zscore"))
  gsva <- gsva[,order(gsva_HIV_pos_CREB)] %>% as.matrix(.)
}) 



gsva_HIV_pos_chemok_s36_logit_prep <- sapply(names(gsva_HIV_pos_chemok_s36), simplify = F, USE.NAMES = T, function(x){
  
  df <- t(gsva_HIV_pos_chemok_s36[[x]]) %>%
                              as.data.frame(.) %>%
                              rownames_to_column("SampleID") %>%
                              inner_join(., pData(eset_ave) %>% rownames_to_column("SampleID"), by = "SampleID" ) %>%
                              mutate(`HIV infection` = ifelse(`HIV infection` == "Yes", 1, 0 )) %>%
                              dplyr::rename(HIV_infection  = `HIV infection`) %>%
                              mutate(donor = as.character(donor)) %>%
                              inner_join(., pData_clinical, by ="donor") %>%
                              dplyr::rename(Study36_Chemokine_genemania = x) %>%
                              mutate(dem_sex = factor(dem_sex)) %>%
                              mutate(Chemokine_tertiles = ntile(Study36_Chemokine_genemania, n = 3)) %>%
                              mutate(Chemokine_sub = ifelse(Chemokine_tertiles == 1, "low", 
                                                       ifelse(Chemokine_tertiles == 2, "medium", "high"))) %>%
                              mutate(Chemokine_sub  = factor(Chemokine_sub, levels = c("low", "medium", "high"))) %>%
                              mutate(censored = ifelse(infect == "Yes", 1, 0)) %>%
                              
                              mutate(time_to_infect = (time_to_infect /365) *12)
  
  
})
                
#HIV_acq_downsampling <- do.call("rbind",lapply(c(1:100), function(x){


cytok_s36_boxplot <- ggboxplot(gsva_HIV_pos_chemok_s36_logit_prep, x = "infect", y = "Study36_Chemokine_genemania", color = "infect")




rv144_logit_chemok_sub <- sapply(names(gsva_HIV_pos_chemok_s36_logit_prep), simplify = F, USE.NAMES = T, function(y){
  out <- sapply(c("low_vs_high", "medium_vs_high", "low_vs_medium"), simplify = F, USE.NAMES = T, function(x){
        groups <- str_split(x, pattern = "_vs_")[[1]]
        print(groups)
         df <- gsva_HIV_pos_chemok_s36_logit_prep[[y]] %>%
                filter(Chemokine_sub %in% groups) %>%
                mutate(contrast = ifelse(Chemokine_sub == groups[1], "0", "1")) 
         model <- glm(HIV_infection~dem_sex + BRA_risk + contrast,  data = df, family = "binomial")
         return(tidy(model))
    })
  
  
  
  
}) 


gsva_HIV_pos_Chemokine_surv <- gsva_HIV_pos_chemok_s36_logit_prep 
surv_object_chemokine <- survival::Surv(time = gsva_HIV_pos_Chemokine_surv$time_to_infect, event = gsva_HIV_pos_Chemokine_surv$censored) 
fit1_chemokine <- survival::survfit(surv_object ~ Chemokine_sub, data = gsva_HIV_pos_Chemokine_surv)
#fit1_chemokine<- coxph(surv_object_chemokine ~ Chemokine_sub, data = gsva_HIV_pos_Chemokine_surv)
surv_Chemokine_curve <- ggsurvplot(fit1_chemokine, data =gsva_HIV_pos_Chemokine_surv, pval = TRUE, fun = "event",
          # risk.table = T,
           break.x.by = 6, 
           break.y.by = 0.1,
           ylim = c(0, 0.4),
           xlab = "Months after Week 26",
           ylab = "Cumulative %\n of infected patients",
          legend.labs = c("Low", "Medium", "High"),
          legend.title = "Chemokine subgroups (tertiles)") +
        theme_survminer(base_size = 8) +
        theme(test = element_text(family = "Arial")) %>%
        guides(colour = guide_legend(nrow = 2))
        ggsave("output/figures/survival_curve_RV144_chemokinesStudy36.pdf", device = "pdf", height =4, width =4 , units = "in")

#surv_pw <- pairwise_survdiff(Surv(time_to_infect, event =  censored) ~ CREB_sub, data = gsva_HIV_pos_CREB_surv)

#write.csv(tidy(surv_pw), file = "output/data/survival_pairwise.csv")
pdf("output/figures/survival_curve_RV144_chemokines.pdf", width = 5, height = 4)
surv_Chemokine_curve
dev.off()





```

```{r adj_funct_network}

functional_adj_network_table <- leadingEdge_hiv_corr_upd %>%
      separate_rows(leadingEdge, sep = "; ")  %>%
      # mutate(CREB_target =  ifelse(leadingEdge %in% c(encode_CREB_genes, geneIds(CHEA_CREB)$CREB1),
      #                                         "Direct Target", ifelse(leadingEdge %in% c(transfac_CREB_genes,
      #                                                                                    jasper_CREB_genes,
      #                                                                             geneIds(putative_CREB)[[1]]), 
      #                                                                 "Putative Target", "--" ))) %>%
      dplyr::rename(source = "pathway",
                    target = "leadingEdge") %>%
      dplyr::select(source, target, new_name)
      #dplyr::select(-pathway) %>%
     

write.table(functional_adj_network_table, sep = "\t", quote = F, file = "output/data/functional_adjuvant_network_table.txt", 
            row.names = F)

functional_adj_node_table <- bind_rows(data.frame("node"  = unique(functional_adj_network_table$source)),
                                       data.frame("node"  = unique(functional_adj_network_table$target))) %>%
                              mutate(node_type = ifelse(node %in% functional_adj_network_table$source, "pathway",
                                     "gene")) %>%
                              left_join(., leadingEdge_hiv_corr_upd %>% dplyr::select(-leadingEdge),
                                        by = c("node" = "pathway" )) %>%
                              mutate(new_name = gsub("_", " ", new_name)) %>%
                              dplyr::rename(label = "new_name") %>%
                              mutate(label = ifelse(is.na(label), node, label)) %>%
                              mutate(CREB_target =  ifelse(node %in% c(encode_CREB_genes, geneIds(CHEA_CREB)$CREB1),
                                              "Direct Target", ifelse(node %in% c(transfac_CREB_genes,
                                                                                         jasper_CREB_genes,
                                                                                  geneIds(putative_CREB)[[1]]), 
                                                                      "Putative Target", "--" ))) %>%
                              mutate(CREB_target = ifelse(node_type == "pathway", "pathway", CREB_target )) %>%
                              left_join(.,bind_rows(chemok_hiv_pos_ledge_temp) %>% 
                                          dplyr::select(pathway, NES), by = c("node" = "pathway" )) %>%
                              mutate(NES  =  ifelse(is.na(NES), 0, NES))

write.table(functional_adj_node_table, sep = "\t", quote = F, file = "output/data/functional_adjuvant_node_table.txt",
            row.names = F)





%>%
      inner_join(., bind_rows(chemok_hiv_pos_ledge_temp) %>% dplyr::select(-leadingEdge), by = "pathway")



```


```{r CREB1 ledge_overlaps}

tf_overlap <- c("THAP11","CCND1","TBX5","PDX1", "CREB1")

select_tf_ledges <- fgsea_analysis_titers$wk26_V1V2$CHEA$output %>%
                      filter(pathway %in% tf_overlap) %>%
                      unnest(cols = "leadingEdge") %>%
                      split(., f = .$pathway) %>%
                      map( ~.x %>% .$leadingEdge)
                    

extract_superset_pvalues <- function(superset){
  df <- summary(superset)$Table %>%
          as.data.frame() %>%
          dplyr::select(-Elements)
  return(df)
}

subset_mset <- function(mset, Interactions){
  mset_in <- mset
  
  mset_in[["overlap.sizes"]] <- mset$overlap.sizes[names(mset$overlap.sizes) %in% Interactions]
  mset_in[["overlap.expected"]] <- mset$overlap.expected[names(mset$overlap.expected) %in%
                                                           Interactions]
  
  mset_in[["P.value"]] <- mset$P.value[names(mset$P.value) %in%
                                                           Interactions]
  return(mset_in)
}


res_select_tf <- supertest(select_tf_ledges, n = dim(exprs(eset_BL_ave))[1])

res_select_tf_p <- extract_superset_pvalues(res_select_tf ) 


sig_contrasts_tf <- row.names(res_select_tf_p[!is.na(res_select_tf_p$P.value),])

write_tsv(res_select_tf_p, "output/rv144_select_tf_overlap_chip_overlap_pvalues.txt")

pdf("output/figures/select_tf_ledgeOverlap_barplot.pdf", width = 9)
plot(subset_mset(res_select_tf, Interactions = sig_contrasts_tf), 
     sort.by="size", margin=c(2,6,2,8), color.scale.pos=c(0.85,1),
     legend.pos=c(0.9,0.15), Layout="landscape")
dev.off()





```


```{r export_tables}

lapply(names(fgsea_analysis_prepost), function(x){
  lS <- fgsea_analysis_prepost[[x]]
  df <- do.call("rbind", lapply(intersect(names(lS), c("CHEA", "c2", "c3","c5", "interferome")), function(y){
    out <- lS[[y]]$output %>%
            filter(pval <0.05) %>%
            unnest(cols = "leadingEdge") %>%
            mutate(tmp = leadingEdge) %>%
            group_by(pathway) %>%
            mutate(leadingEdge = paste(tmp, collapse = "; ")) %>%
            ungroup() %>%
            dplyr::select(-tmp) %>% unique() %>%
            mutate(geneset = y)
  }))
  write_tsv(df, path = paste("../data_tables/gsea/RV144/", x, ".txt", sep = ""))
})

lapply(names(fgsea_analysis_titers), function(x){
  lS <- fgsea_analysis_titers[[x]]
  df <- do.call("rbind", lapply(intersect(names(lS), c("CHEA", "c2", "c3","c5", "interferome")), function(y){
    out <- lS[[y]]$output %>%
            filter(pval <0.05) %>%
            unnest(cols = "leadingEdge") %>%
            mutate(tmp = leadingEdge) %>%
            group_by(pathway) %>%
            mutate(leadingEdge = paste(tmp, collapse = "; ")) %>%
            ungroup() %>%
            dplyr::select(-tmp) %>% unique() %>%
            mutate(geneset = y)
  }))
  write_tsv(df, path = paste("../data_tables/gsea/RV144/", x, ".txt", sep = ""))
})

lapply(names(fgsea_analysis_hiv_pos), function(x){
  lS <- fgsea_analysis_hiv_pos[[x]]
  df <- do.call("rbind", lapply(intersect(names(lS), c("CHEA", "c2", "c3","c5", "interferome")), function(y){
    out <- lS[[y]]$output %>%
            filter(pval <0.05) %>%
            unnest(cols = "leadingEdge") %>%
            mutate(tmp = leadingEdge) %>%
            group_by(pathway) %>%
            mutate(leadingEdge = paste(tmp, collapse = "; ")) %>%
            ungroup() %>%
            dplyr::select(-tmp) %>% unique() %>%
            mutate(geneset = y)
  }))
  write_tsv(df, path = paste("../data_tables/gsea/RV144/", x, ".txt", sep = ""))
})

write_tsv(fits_rv144_prepost_vaxx$topTable %>%
             arrange(desc(t)) %>%
            mutate(rank = row_number()) , path = "../data_tables/contrasts/RV144/post_vs_pre_vaccine.txt")


write_tsv(fits_rv144$topTable %>%
             arrange(desc(t)) %>%
            mutate(rank = row_number()) , path = "../data_tables/contrasts/RV144/wk26_V1V2_titers.txt")

write_tsv(fits_rv144_hiv_pos$topTable %>%
             arrange(desc(t)) %>%
            mutate(rank = row_number()) , path = "../data_tables/contrasts/RV144/hiv_pos_vs_neg.txt")




```