---
title: "RV144_integration"
author: "Adam Pelletier"
date: "10/4/2019"
output: html_document
---


```{r setup, message = FALSE, warning=FALSE}
suppressPackageStartupMessages(library(rstudioapi))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(pheatmap))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(biomaRt))
suppressPackageStartupMessages(library(GSEABase))
suppressPackageStartupMessages(library(fgsea))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(tibble))
suppressPackageStartupMessages(library(GSVA))
suppressPackageStartupMessages(library(cluster))
suppressPackageStartupMessages(library(apeglm))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(sva))
suppressPackageStartupMessages(library(affy))
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(GSVA))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(survminer))
suppressPackageStartupMessages(library(janitor))
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(getwd())
```

```{r }

setup_dir <- function(dir_string) { 
  ### Verifies creates a directory if it doesn't exist. Returns the dir_path
  if (dir.exists(dir_string)){
    dir_set <- dir_string
  } else {
    dir.create(dir_string) 
    dir_set <- dir_string
  }
  return(dir_set)
}


inputDir <- setup_dir("input")
outDir <- setup_dir("output")

genesetsDir <- setup_dir("../input/genesets")
figureDir <- setup_dir(file.path(outDir,"figures"))
dataOutDir <- setup_dir(file.path(outDir,"data"))


```


```{r all_DEG_list}
post_vaxx_degs <- fits_rv144_prepost_vaxx$topTable %>%
                  filter(P.Value < 0.05) %>%
                  #filter(adj.P.Val < 0.05) %>%
                  filter(SYMBOL != "") %>%
                  .$SYMBOL


titer_corr_degs <-   fits_rv144$topTable %>%
          filter(P.Value < 0.05) %>%
          #filter(adj.P.Val < 0.05) %>% 
          filter(SYMBOL %in% post_vaxx_degs) %>%
          filter(SYMBOL != "") %>%
          .$SYMBOL


# titer_corr_degs <- c()
# for(i in names(split_fits_titers)){
#   for(j in names(split_fits_titers[[i]]))
#     concat <- paste(i,j, sep = "__")
#   deg <- split_fits_titers[[i]][[j]]$topTable[[concat]] %>%
#           filter(P.Value < 0.05) %>%
#           #filter(adj.P.Val < 0.05) %>% 
#           filter(BROAD.Gene.Symbol %in% post_vaxx_degs) %>%
#           filter(BROAD.Gene.Symbol != "") %>%
#           .$BROAD.Gene.Symbol
#   titer_corr_degs <- unique(c(titer_corr_degs, deg))
# }



```

```{r biomart_GO_annot}
mart = useMart("ensembl", dataset="hsapiens_gene_ensembl")


ensembl_id <-  getBM(attributes= c("hgnc_symbol","ensembl_gene_id"),
                  filters = 'hgnc_symbol', values = titer_corr_degs, mart = mart)




go_ids <-  getBM(attributes= c("ensembl_gene_id", "go_id", "name_1006", "namespace_1003"),
                  filters = 'ensembl_gene_id', values = ensembl_id$ensembl_gene_id, mart = mart) 


immune_filter <- c("CHEMOKINE","CYTOKINE", "CXCR[0-9]+", "CXCL[0-9]+", "CCR[0-9]+", "CCL[0-9]+","T( |)CELLS","B( |)CELLS",
                   "FOLLICULAR", "DENDRITIC", "TREG", "TH(1|2)", "TGF(-|)B",
                   "TNF(A|AR|1R|R)", "FRACTALKINE", "EOTAXIN", "INTERLEUKIN", "IL(-|)[0-9]+", "IFN", "INTERFERON", "MHC", 
                   "ANTIGEN( |_)PRESENTATION", "ANTIBODY", "TCR", "BCR", "NFKB", "RELB", "TLR[0-9]", 
                   "TOLL-LIKE", "MYD88", "TRAF", "INFLAMMASOME", "NLR", "NOD-LIKE", "CTLA", "PD(|-)(|L)1","4(|-)1BB","MCSF")
immune_filter_comb <- paste(c(immune_filter, tolower(immune_filter)), collapse = "|")

go_ids_immune_temp <- go_ids %>%
                filter(grepl(immune_filter_comb,name_1006)) %>%
                dplyr::select(go_id, name_1006) %>%
                unique(.)

writexl::write_xlsx(go_ids_immune_temp, path = file.path(dataOutDir, "go_term_category_filters.xlsx"))



go_ids_immune <- read_excel(path = file.path(dataOutDir, "go_term_category_filters_upd.xlsx")) %>%
                  filter(keep == 1)

immune_gene_ids <- merge(ensembl_id,go_ids, by  = "ensembl_gene_id") %>%
                  filter(go_id %in% go_ids_immune$go_id) %>%
                  .$hgnc_symbol %>%
                  unique(.)


### GO Accession numbers were taken at https://www.ebi.ac.uk/QuickGO/term/GO:0003700 for transcription factor activity

tf_go_ids <- c("GO:0003700","GO:0000130", "GO:0001071", "GO:0001130", "GO:0001131", 
                                  "GO:0001151", "GO:0001199", "GO:0001204")
tf_gene_ids <- merge(ensembl_id, go_ids, by = "ensembl_gene_id") %>%
              filter(go_id %in% tf_go_ids) %>%
              .$hgnc_symbol %>%
                  unique(.)


filtered_gene_ids <- c(immune_gene_ids, tf_gene_ids)


```



```{r gsva_CREB_sig}



titer_correlates <- exprs(eset_corr_titer) %>%
                  as.data.frame(.) %>%
                  rownames_to_column("Illmn.ID") %>%
                  gather(Sample.ID, value, -Illmn.ID) %>%
                  inner_join(., fData(eset_corr_titer) %>% rownames_to_column("Illmn.ID"), by = "Illmn.ID") %>%
                  dplyr::select(SYMBOL, Sample.ID, value) %>%
                  filter(SYMBOL %in% filtered_gene_ids) %>%
                  filter(SYMBOL %in% titer_corr_degs) %>%
                  group_by(SYMBOL, Sample.ID) %>%
                  mutate(mean = mean(value)) %>%
                  ungroup(.) %>%
                  dplyr::select(-value) %>%
                  unique(.) %>%
                  filter(!grepl(" ///", SYMBOL)) %>%
                  spread(SYMBOL, mean) 


```



```{r correlate_with_degs}


deg_creb_corr <- gsva_titers_CREB %>%
                as.data.frame(.) %>%
                rownames_to_column("CHEA_TF") %>%
                gather(sample, zscore, -CHEA_TF) %>%
                inner_join(.,titer_correlates, by = c("sample" = "Sample.ID")) %>%
                gather(gene, expr_value, -CHEA_TF, -sample, -zscore) %>%
                group_by(gene) %>%
                do(model = cor.test(.$expr_value , .$zscore, method = "spearman")) %>%
                tidy(., model) %>%
                ungroup(.) %>%
                filter(p.value < 0.05) %>%
                mutate(direction = ifelse(sign(estimate) == 1, "UP", "DOWN")) %>%
                filter(direction == "UP")
    


sig_TF_CHEA <- as.data.frame(fgsea_analysis_titers$wk26_V1V2$CHEA$output) %>%
                filter(pval < 0.05) %>%
                filter(sign(NES) == 1) %>%
                unnest(leadingEdge) %>%
                filter(pathway != "CREB1") %>%
                split(., f = .$pathway)
                

tf_gsva <- do.call("rbind", lapply(names(sig_TF_CHEA), function(x){
  LE <- sig_TF_CHEA[[x]]$leadingEdge
  exprs_mat <- exprs(eset_corr_titer) %>%
                  as.data.frame(.) %>%
                  rownames_to_column("Illmn.ID") %>%
                  gather(Sample.ID, value, -Illmn.ID) %>%
                  inner_join(., fData(eset_corr_titer) %>% rownames_to_column("Illmn.ID"), by = "Illmn.ID") %>%
                  dplyr::select(SYMBOL, Sample.ID, value) %>%
                  filter(SYMBOL %in% LE) %>%
                  spread(Sample.ID, value) %>%
                  column_to_rownames("SYMBOL") %>%
                  as.matrix(.)
  gs <- CHEA[names(CHEA) == x]
  gsva_TF <- gsva(expr = exprs_mat, gs, method = "zscore" )
  return(gsva_TF)
}))

  
corr_TF_CREB <- as.data.frame(gsva_titers_CREB) %>%
                  rownames_to_column("CREB_CHEA") %>%
                  gather(sample, CREB_zscore, -CREB_CHEA) %>%
                  inner_join(., as.data.frame(t(tf_gsva)) %>% rownames_to_column("sample"), by ="sample" ) %>%
                  gather(TF_CHEA, TF_zscore, -CREB_CHEA, -sample, -CREB_zscore) %>%
                  group_by(TF_CHEA) %>%
                  do(model = cor.test(.$TF_zscore, .$CREB_zscore, method = "spearman")) %>%
                  tidy(., model) %>%
                  ungroup(.) %>%
                  filter(sign(estimate) == 1 & p.value < 0.05)

study36_selected_TFs <- sapply(excel_sheets("../output/data/selected_TF_nodes_network.xlsx"), simplify = F, 
                            USE.NAMES = T, function(x){
  tf <- read_excel("../output/data/selected_TF_nodes_network.xlsx", sheet = x) %>%
          .$node_name
  return(tf)
})


#  Count how many leading edge genes are common to CREB correlates, and select the top 10 weight up TFs with the most common targets. Prioritize TF that are in the study36 DC network by weighing up their count
TF_LE_stats <- as.data.frame(fgsea_analysis_titers$wk26_V1V2$CHEA$output) %>%
                 filter(pathway %in% corr_TF_CREB$TF_CHEA) %>%
                  unnest(leadingEdge) %>%
                  filter(leadingEdge %in% deg_creb_corr$gene) %>%
                  group_by(pathway) %>%
                  mutate(LE_count = n()) %>%
                  ungroup(.) %>%
                  filter(LE_count > 0) %>%
                  #mutate(LE_count = ifelse(pathway %in% study36_selected_TFs$DC & LE_count > 1, LE_count + 100, LE_count)) %>% 
                  # mutate(LE_count = ifelse(pathway %in% unique(unlist(study36_selected_TFs, use.names = F)) & LE_count > 1,
                  #                          LE_count + 100, LE_count)) %>%
                  dplyr::select(pathway, LE_count) %>%
                  unique(.) %>%
                  top_n(.,10, LE_count)

TF_LE_stats_raw <- as.data.frame(fgsea_analysis_titers$wk26_V1V2$CHEA$output) %>%
                 filter(pathway %in% corr_TF_CREB$TF_CHEA) %>%
                  unnest(leadingEdge) %>%
                  mutate(inLedge = ifelse(leadingEdge %in% deg_creb_corr$gene, 1, 0)) %>%
                  group_by(pathway) %>%
                  mutate(ledge_overlap = sum(inLedge)) %>%
                  ungroup(.) %>%
                  dplyr::select(pathway, ledge_overlap)  %>%
                  unique(.)

WriteXLS::WriteXLS(TF_LE_stats_raw, "output/data/RV144_TF_unfiltered.xlsx")


selected_TF_LE_genes <- as.data.frame(fgsea_analysis_titers$wk26_V1V2$CHEA$output) %>%
                 filter(pathway %in% corr_TF_CREB$TF_CHEA) %>%
                  unnest(leadingEdge) %>%
                  filter(leadingEdge %in% deg_creb_corr$gene) %>%
                  filter(pathway %in% TF_LE_stats$pathway) %>%
                  mutate(node = paste(pathway, leadingEdge, sep = "_")) 


encode <- getGmt("../input/genesets/ENCODE-tf.gmt") 
encode_CREB_genes <- geneIds(encode[names(encode) == "CREB1"])[[1]]
transfac <- getGmt("../input/genesets/TRANSFAC.gmt")
transfac_CREB_genes <- geneIds(transfac[names(transfac) == "CREB1"])[[1]]
jasper <- getGmt("../input/genesets/JASPER-tf.gmt")
jasper_CREB_genes <- geneIds(jasper[names(jasper) == "CREB1"])[[1]]   
putative_CREB <- getGmt("../input/genesets/putative_CREB1_targets.gmt")
 

creb_target_table <- selected_TF_LE_genes %>%
                    mutate(CREB_target = ifelse(leadingEdge %in% c(transfac_CREB_genes, geneIds(putative_CREB)[[1]], 
                                                              jasper_CREB_genes ),"putative", "none")) %>%
                    mutate(CREB_target = ifelse(leadingEdge %in% c(encode_CREB_genes,geneIds(CHEA_CREB)[[1]] ), "target",
                                                CREB_target)) %>%
                    dplyr::select(node, CREB_target)



node_gene_table <- selected_TF_LE_genes %>%
                inner_join(., deg_creb_corr, by = c("leadingEdge" = "gene")) %>%
                dplyr::select(node, leadingEdge, estimate ) %>%
                rename(node_value = "estimate",
                       node_name = "leadingEdge") %>%
                mutate(node_value = sign(node_value),
                       node_type = "gene") 

CREB_node_table <- fgsea_analysis_titers$wk26_V1V2$CHEA$output %>%
                    filter(pathway == "CREB1") %>%
                    mutate(node = paste(pathway, "CHEA", sep = "_")) %>%
                    mutate(node_value = sign(NES),
                           node_type = "module") %>%
                    rename(node_name = "pathway") %>%
                    dplyr::select(node, node_name, node_value, node_type)

tf_node_table <- fgsea_analysis_titers$wk26_V1V2$CHEA$output %>%
                     filter(pathway %in% TF_LE_stats$pathway) %>%
                      mutate(node = pathway,
                             node_name = pathway,
                             node_value = sign(NES),
                             node_type = "TF_module") %>%
                      dplyr::select(node, node_name, node_value, node_type)
 
merged_node_table <- do.call("rbind", list(CREB_node_table, tf_node_table, node_gene_table)) %>%
                      mutate(CREB_target = ifelse(node_name %in% c(transfac_CREB_genes, geneIds(putative_CREB)[[1]], 
                                                              jasper_CREB_genes ),"putative", "none")) %>%
                      mutate(CREB_target = ifelse(node_name %in% c(encode_CREB_genes,geneIds(CHEA_CREB)[[1]] ), "target",
                                                CREB_target)) 

write.table(merged_node_table, file = file.path(outDir, "nodes_table_RV144.csv"), quote = FALSE, row.names = FALSE, sep = "!")  

write.table(unique(merged_node_table[merged_node_table$node_type == "gene",]$node_name), quote = F, file = file.path(outDir, "clueGO_UP_input_RV144.txt"), row.names = F, col.names = F)

write.table(deg_creb_corr[deg_creb_corr$direction == "UP",]$gene, quote = F, file = file.path(outDir, "clueGO_UP_input_RV144_all_nonimmune.txt"), row.names = F, col.names = F)


tf_edge_table <- selected_TF_LE_genes %>%
                  dplyr::select(pathway, node) %>%
                  rename(source = "pathway",
                         target = "node") %>%
                  mutate(edge_value = 1, 
                         edge_type = "leadingEdge_overlap",
                         annotation = "TF_target",
                         edge_color = "turquoise") 

creb_edge_table <- node_gene_table %>%
                  inner_join(., deg_creb_corr, by = c("node_name" = "gene")) %>%
                  mutate(source = "CREB1_CHEA") %>%
                  rename(target = "node", 
                         edge_value = "estimate") %>%
                  mutate(edge_type = "spearman_rhp",
                         annotation = "regression",
                         edge_color = "red") %>%
                  dplyr::select(source, target, edge_value, edge_type, annotation, edge_color)

merged_network_table <- rbind(creb_edge_table, tf_edge_table)

                  
write.csv(merged_network_table, file = file.path(outDir, "network_table_CREB_RV144.csv"), quote = FALSE,
                                                     row.names = FALSE)


```


```{r network_overlap}

study36_TFs_all <- do.call("rbind", lapply(excel_sheets("../output/data/TFs_correlated_to_CREB.xlsx"), function(x){
      df <- read_excel("../output/data/TFs_correlated_to_CREB.xlsx", sheet = x) %>%
              mutate(population = x) %>%
              filter(NES > 0) %>%
              dplyr::select(pathway, population ) %>%
              unique(.)
    return(df)
})) %>%
  group_by(pathway) %>%
  mutate(study36_population = paste(population, collapse = ", ")) %>%
  ungroup(.) %>%
  dplyr::select(-population) %>%
  unique(.)



study36_rv144_network_overlap <- tf_node_table %>%
                                  inner_join(., study36_TFs_all, by = c("node" = "pathway")) %>%
                                  dplyr::select(node, study36_population)

write.csv(study36_rv144_network_overlap, file = "output/data/study36_rv144_TF_overlap.csv")





```

#generate large geneset from TF in Fig3D, generate global zscore, spit into tertiles, kaplan meier 
```{r global_TF_hiv_acq}

global_TF_ledge <- fgsea_analysis_hiv_pos$`HIV_Pos_VACCINE-HIV_Neg_VACCINE`$CHEA$output %>%
                      filter(pathway %in% study36_rv144_network_overlap$node) %>%
                      filter(padj < 0.05) %>%                    
                      unnest(cols = "leadingEdge") %>%
                      .$leadingEdge %>%
                      unique()
TF_global <- GeneSetCollection(list(GeneSet(setName = "Study36_TF_global",  
                                geneIds = unique(global_TF_ledge))))


TF_global_filt_HIV_pos_df <- exprs(eset_ave) %>%
                        as.data.frame(.) %>%
                        rownames_to_column("IlmnID") %>%
                        gather(sample, value, -IlmnID) %>%
                        inner_join(., pData(eset_ave), by = c("sample" = "Sample name")) %>%
                        filter(stimulation == "DMSO" & treatment == "VACCINE") %>%
                        inner_join(., fData(eset_ave), by = "IlmnID") %>%
                        filter(SYMBOL %in% global_TF_ledge)

expr_mat_gsva_HIV_pos_TF_global <- TF_global_filt_HIV_pos_df %>%
                        dplyr::select(sample, SYMBOL, value) %>%
                        spread(sample, value) %>%
                        column_to_rownames("SYMBOL") %>%
                        as.matrix(.)

annot_gsva_HIV_pos_TF_global <- TF_global_filt_HIV_pos_df %>%
                        dplyr::select(sample, `HIV infection` ) %>%
                        unique(.) %>%
                        rowid_to_column("rowid") %>%
                        dplyr::select(-rowid) %>%
                        #unique(.) %>%
                        column_to_rownames("sample")


gsva_HIV_pos_TF_global <- as.data.frame(gsva(expr_mat_gsva_HIV_pos_TF_global, TF_global, method = "zscore"))
gsva_HIV_pos_TF_global <- gsva_HIV_pos_TF_global[,order(gsva_HIV_pos_CREB)] %>% as.matrix(.)



gsva_HIV_pos_TF_global_logit_prep <- t(gsva_HIV_pos_TF_global) %>%
                              as.data.frame(.) %>%
                              rownames_to_column("SampleID") %>%
                              inner_join(., pData(eset_ave) %>% rownames_to_column("SampleID"), by = "SampleID" ) %>%
                              mutate(`HIV infection` = ifelse(`HIV infection` == "Yes", 1, 0 )) %>%
                              dplyr::rename(HIV_infection  = `HIV infection`) %>%
                              mutate(donor = as.character(donor)) %>%
                              inner_join(., pData_clinical, by ="donor") %>%
                              mutate(dem_sex = factor(dem_sex)) %>%
                              mutate(TF_global_tertiles = ntile(Study36_TF_global, n = 3)) %>%
                              mutate(TF_global_sub = ifelse(TF_global_tertiles == 1, "low", 
                                                       ifelse(TF_global_tertiles == 2, "medium", "high"))) %>%
                              mutate(TF_global_sub  = factor(TF_global_sub, levels = c("low", "medium", "high"))) %>%
                              mutate(censored = ifelse(infect == "Yes", 1, 0)) %>%
                              
                              mutate(time_to_infect = (time_to_infect /365) *12)
                
#HIV_acq_downsampling <- do.call("rbind",lapply(c(1:100), function(x){







rv144_logit_TF_global_sub <- sapply(c("low_vs_high", "medium_vs_high", "low_vs_medium"), simplify = F, USE.NAMES = T, function(x){
  groups <- str_split(x, pattern = "_vs_")[[1]]
  print(groups)
   df <- gsva_HIV_pos_TF_global_logit_prep %>%
          filter(TF_global_sub %in% groups) %>%
          mutate(contrast = ifelse(TF_global_sub == groups[1], "0", "1")) 
   model <- glm(HIV_infection~dem_sex + BRA_risk + contrast,  data = df, family = "binomial")
   return(tidy(model))
})


gsva_HIV_pos_TF_global_surv <- gsva_HIV_pos_TF_global_logit_prep 
surv_object_TF_global <- survival::Surv(time = gsva_HIV_pos_TF_global_surv$time_to_infect, event = gsva_HIV_pos_TF_global_surv$censored) 
fit1_TF_global <- survival::survfit(surv_object ~ TF_global_sub, data = gsva_HIV_pos_TF_global_surv)
#fit1_chemokine<- coxph(surv_object_chemokine ~ Chemokine_sub, data = gsva_HIV_pos_Chemokine_surv)
surv_TF_global_curve <- ggsurvplot(fit1_TF_global, data =gsva_HIV_pos_TF_global_surv, pval = F, fun = "event",
          # risk.table = T,
           break.x.by = 6, 
           break.y.by = 0.1,
           ylim = c(0, 0.4),
           xlab = "Months after Week 26",
           ylab = "Cumulative %\n of infected patients",
          legend.labs = c("Low", "Medium", "High"),
          legend.title = "Global TF signature  subgroups (tertiles)") +
        theme_survminer(base_size = 8) +
        theme(test = element_text(family = "Arial")) %>%
        guides(colour = guide_legend(nrow = 2))
        ggsave("output/figures/survival_curve_RV144_Global_TF.pdf", device = "pdf", height =4, width =4 , units = "in")

#surv_pw <- pairwise_survdiff(Surv(time_to_infect, event =  censored) ~ CREB_sub, data = gsva_HIV_pos_CREB_surv)

#write.csv(tidy(surv_pw), file = "output/data/survival_pairwise.csv")










```